### ISSUE TITLE
Modify Guide.sh to be single interface for Docker or Singularity runs of NGIAB

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB-CloudInfra#113]
For UI efficiency, what if we added a `--singularity` option to the guide.sh to trigger execution using singularity containers instead of docker? 

That option would come in somewhere here: 
https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/81c053c775c78840617033d9baf5eb89b236e5d0/guide.sh#L130-L182

**Comment by jameshalgren** [comment]
@arpita0911patel

**Comment by arpita0911patel** [comment]
Closing this issue as we planned to have separate repo for both.
