### ISSUE TITLE
Consider merging (for CI efficiency) with ngen-singularity

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB-CloudInfra#114]
The NGEN-Singularity repository has permitted the development of an "HPC-Friendly" version of NGIAB. There could be some efficiencies obtained by merging that repository with this one.

https://github.com/CIROH-UA/Ngen-Singularity

**CRITICAL** 
We need to make sure that we are a little over cautious with the initial testing on this to make sure that whatever we set up for automated CI (e.g., github runners, AWS, etc.) is producing artifacts that actually work on at least a few of our target environments (e.g., Pantarhei, Wukong, UAHPC, etc.)

**Comment by jameshalgren** [comment]
@hellkite500

**Comment by benlee0423** [comment]
1. create singulariry directory in NGIAB-CloudInfra
2. Move all content in [Ngen-Singularity](https://github.com/CIROH-UA/Ngen-Singularity) repo.
3. Move guide.sh in root directory to docker.

**Comment by arpita0911patel** [comment]
Blocked due to https://github.com/CIROH-UA/Ngen-Singularity/issues/12 which is blocked due to https://github.com/NOAA-OWP/ngen/pull/755

**Comment by arpita0911patel** [comment]
As of now plan is to keep NGIAB-HPCInfra repo separate. Please reopen this later if needed.
