### ISSUE TITLE
Improve Guide.sh error handling

### ISSUE THREAD

**Issue by chp2001** [CIROH-UA/NGIAB-CloudInfra#115]
Ran into some difficulty when getting started due to errors being relatively unhelpful- There doesn't seem to be any significant validation on path / file inputs before running commands, so any "file not found" errors appear a fair bit into the execution, and on non-descriptive line numbers.

Ideally there's some method to check the input file paths before beginning to run the overall program, and give feedback on the validity of the inputs, and stopping execution if necessary.
I.e. if the input dataset is missing a forcing file, catching that before spending a few minutes generating catchment data and such would be very useful.
On further inspection, the "errors" are being printed, but don't stand out or stop execution, so are easy to miss.

Definitely not a high priority, as it's primarily a barrier to entry for inexperienced users, but this difficulty could be mentioned somewhere in documentation, or errors in general could have terminal coloring applied.

![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/7992111/dcf8f278-7929-48fc-b66a-28b2fdfb095a)
As mentioned, the relevant errors don't really stand out, especially when other things are colorful.

**Comment by benlee0423** [comment]
@chp2001 
I have created a PR at #133 .
Can you take a look at it?
