### ISSUE TITLE
AWS Resource request to deploy SWE-ML models

### ISSUE THREAD

**Issue by karnesh** [CIROH-UA/NGIAB-CloudInfra#117]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Karnesh Jain – [kjain1@ua.edu](mailto:kjain1@ua.edu) - University of Alabama

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

Looking to find a place for SWE-ML model to live. It will run daily and save the output to AWS S3 storage. Currently, it is run on a local machine by a user. We want it to be deployed on AWS EC2 and run it on daily basis automatically. 

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

Current version of SWE-ML model and workflow have been developed in Python. 

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

## List of AWS Services

- EC2 – It will be used to run ML models on daily basis.
- Sagemaker – It is needed to run the Jupyter notebooks of SWE-ML.

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
We will begin using the resources right away.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
No.

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
@karnesh - you should have access to UA subaccount. Please try that or check with me on slack.

**Comment by arpita0911patel** [comment]
@karnesh - let us know if this is good to close.
