### ISSUE TITLE
Pantarhei access request to deploy SWE-ML models

### ISSUE THREAD

**Issue by karnesh** [CIROH-UA/NGIAB-CloudInfra#118]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Karnesh Jain – [kjain1@ua.edu](mailto:kjain1@ua.edu) - University of Alabama

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

Looking to find a place for SWE-ML model to live. It will run daily and save the output to AWS S3 storage. Currently, it is run on a local machine by a user. We want it to be deployed on Pantarhei and run it on daily basis automatically.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

Current version of SWE-ML model and workflow have been developed in Python.

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. HPC or VM
  
2. vCPU

3. Memory

4. Disk Space

- Pantarhei Access – It will be used to run SWE-ML model on daily basis.

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
We will begin using the resources right away.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
No.
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Hi Karnesh, please reach out to Trupesh for this.

**Comment by TrupeshKumarPatel** [comment]
Adding Vishnu Sai Karthik Gindi (email: vgindi@crimson.ua.edu) - University of Alabama
