### ISSUE TITLE
Water Prediction Node token authentication

### ISSUE THREAD

**Issue by dylanlee** [CIROH-UA/NGIAB-CloudInfra#120]
## Requester Information:
Dylan Lee, [dlee91@ua.edu](mailto:dlee91@ua.edu)

## Project Information:
This request is for the Water Prediction Node. The Water Prediction Node is creating an experimental catalog that will have restricted access for data that the National Water Center isn't ready to make available to the general public yet. The authentication solution has been created using AWS and will  issue temporary tokens to whitelisted domains (for example: "noaa.gov" or "ua.edu") or specific whitelisted emails. The solution stores temporary tokens in a dynamoDB table and tokens are used to grant access to a data stored in a private S3 bucket that is accessible by a cloudfront distribution that is triggering the token validation. 

A working demo of the project has been created using cloudformation and can be found at: https://github.com/dylanlee/wpn-auth

## Resource Requirements:
- S3: private, bucket name suggestion: wpn-exp-cat. Bucket size: 0-10 Tb.
- DynamoDB: 1 x standard table class, 1 GB standard table size with backup.
- Lambda: x86 architecture, 513 MB ephemeral storage, 100,000 per month (free tier). The current lambdas use ~128 MB of memory or less and usually execute in under 300 ms.
-  API gateway: There will be one API with POST and OPTIONS methods enabled. 
- Cloudfront: 1 cloudfront distribution with a single origin and a default behavior that triggers the lambda authenticator when a viewer makes a request. 
- SES: needed to send tokens to whitelisted emails. SES needs to be setup manually and I want to be able to send emails from the waternode.ciroh.org domain.

## Timeline:
Ideally this would be implemented by the end of March, 2024

## Security and Compliance Requirements:
None

## Budget:
These resources should be tagged Water Node and will be paid for by the Water Node budget.

## Approval:
The Water Node approves the cost of these resources so the main concern is any possible issues integrating the existing demo into CIROH's AWS account.

**Comment by benlee0423** [comment]
Thank you for submitting the request.
Based on the our discussion, I create rough estimate of the cost.
[AWS_Estimate_Water_Node.pdf](https://github.com/CIROH-UA/NGIAB-CloudInfra/files/14454538/AWS_Estimate_Water_Node.pdf)

@dylanlee 
Also, should I combine this cost with existing water node cost, i.e., use the same tag to capture the total cost?

**Comment by dylanlee** [comment]
@benlee0423  Thanks for the cost estimate! I think we should set the dynamodb settings to pay per request/on demand since I don't think the request amount will be high enough to use provisioned capacity. 

Yes lets go ahead and combine the cost with the existing water node cost.

**Comment by dylanlee** [comment]
@benlee0423 I have updated the [solution repository](https://github.com/dylanlee/wpn-auth) to have a mostly working terraform version of the template. The main thing that didn't work for me was getting the CORS right on the api gateway (I just enabled it by hand).

**Comment by arpita0911patel** [comment]
@dylanlee please let us know if we are good to close this ticket and if all the requirements is satisfied.

**Comment by dylanlee** [comment]
Okay I am pretty sure we are there but let me do a bit more testing and then I will let you know tomorrow. Thanks!

**Comment by dylanlee** [comment]
@arpita0911patel  and @benlee0423 yes let's consider this closed. Thanks for all your help!

**Comment by arpita0911patel** [comment]
Thank you, @dylanlee . If you need anything else, please create another ticket, and we'll be glad to assist you. Thank you @benlee0423 for working on this.
