### ISSUE TITLE
Create Exceeding Budget Request Form

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB-CloudInfra#126]
This form would be specifically for projects who anticipate exceeding the $500/month limit. It includes additional fields compared to the regular form, such as justification for the increased budget, expected usage patterns, and approval workflows. Users would need to fill out this form if they require resources beyond the standard allocation.

**1.	Requester Information:**
This should include the name and contact information of the person making the request.

**2.	Link to Existing Infrastructure Ticket:** 
Provide a ticket created for this project for which extension is being requested. 

**3.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**4.	Timeline:** 
Indicate the expected timeline for the extended resource requirement for the project.
 
**5.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
**6.	Cost Estimation:** 
Include the updated cost estimation for your project based on more resource requirements:

AWS Cost Calculator: https://calculator.aws/#/

NOTE: CIROH has AWS Savings plan added to the account and Data Egress Waiver Program signed and available. So please take a note while estimating the Cost.

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 
**7.	Approval:** 
Once Form is submitted, we will email the CIROH management to get the approval.

**8. Project to charge to:**

**Comment by arpita0911patel** [comment]
@jameshalgren let me know if this looks good or we need to add anything more in this form.

**Comment by jameshalgren** [comment]
This is a very useful template -- we could use these to extend the existing request -- in other words, why create a new authorization when what is being requested is essentially an extension to an existing authorization.

**Comment by arpita0911patel** [comment]
yes, this is for extending the existing request so modified the form little more.
