### ISSUE TITLE
Approval to use TEEHR to Process V3.0 Retrospective for PSU Project

### ISSUE THREAD

**Issue by mgdenno** [CIROH-UA/NGIAB-CloudInfra#129]
**1.       Requester Information:**
This should include the name and contact information of the person making the request.
Matthew Denno
[mdenno@rti.org](mailto:mdenno@rti.org)
 
**2.       Link to Existing Infrastructure Ticket:** 
Provide a ticket created for this project for which extension is being requested. 

https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/33
 
**3. Justification for increased budget:**
Please provide technical details for the increased usage.
As part of the evaluation system project we are working with Dr. Shen at PSU and his team to use their work as a benchmark case for comparison with other work. As part of their project they need to process the NWM v3.0 retrospective forcing data to generate mean areal values for precipitation and temperature for the MERIT basins (~200k). The TEEHR toolset, which is deployed to TEEHR-HUB on the CIROH AWS infrastructure, has built-in functionality to efficiently process this data to arbitrary basins.  We would like to utilize TEEHR to process this data for the PSU project but it will put us over the $500 limit if we do.  This data would also be posted to HydroShare or and S3 bucket for use by the broader CIROH community.  See point 3 below for information on estimated costs.
 
**4.       Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.
RTI did a test on TEEHR hub to estimate the time and resources it would take to process the 40-year retrospective to the ~200k MERIT basins.  Based on these tests, we estimate that it will take approximately 100 hours on a r5.4xlarge AWS EC2 instance to process a single parameter.  We would like to process precipitation and temperature, which would require ~200 hours of an r5.4xlarge AWS EC2.  We anticipate this will generate approximately 1.2 TB of hourly timeseries data.
 
**Options:**
1. Cloud Provider: AWS/Azure/GCP
 
2. Required Services in the Cloud:
 
   List of AWS Services
   ====================
- EC2
- S3
 
**5.       Timeline:** 
Indicate the expected timeline for the extended resource requirement for the project.
We would be ready to run this job any time/ASAP.

**6.       Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.

**7.       Cost Estimation:** 
Include the updated cost estimation for your project based on more resource requirements:
200 hours of r5.4xlarge EC2 @ $1.008/hour = $201.60
There would also be some ingress/egress expenses and bucket expenses that are not included but are expected to be in significant.
 
**8.       Approval:** 
Once Form is submitted, we will email the CIROH management to get the approval.
 
**9. Project to charge to: (For CIROH IT Admin to fill out based on approval process) ** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
CIROH management has approved the use of these additional resources for the purpose outlined above. @mgdenno , you are cleared to utilize them accordingly. Closing this ticket. Let us know if anything.
