### ISSUE TITLE
Research in The Sensor-Accelerated Intelligent Learning (SAIL) Laboratory at UA

### ISSUE THREAD

**Issue by jgong-ua** [CIROH-UA/NGIAB-CloudInfra#130]
**1.	Requester Information:**
PI: Jiaqi Gong, Associate Professor of Computer Science.
[jiaqi.gong@ua.edu](mailto:jiaqi.gong@ua.edu)
Postdoc: Chen Wang, postdoc researcher of computer science.
[cwang86@ua.edu](mailto:cwang86@ua.edu)

**2.	Project Information:** 
The NSF-OKN project aims to create a comprehensive knowledge graph to integrate health and justice data for enhancing rural resilience. This project will benefit from existing resources like NSF-funded KnowWhereGraph and contribute to scientific studies in public health and environmental crises. It focuses on leveraging geo-enrichment services and fostering collaborations across various domains to strengthen rural communities' resilience.

**3.  Project Description:**
The project involves developing a multidisciplinary knowledge graph, integrating diverse datasets related to health and justice. This graph will serve as a resource for researchers, practitioners, and educators, aiding in understanding risk environments in rural areas and improving resilience. The software development will focus on data amalgamation, maintaining data quality, and implementing learning mechanisms across varied datasets.

**4.	Resource Requirements:** 
High-Performance Computing (HPC) or Virtual Machines (VM): HPC is essential for efficiently processing and analyzing massive datasets.
Virtual CPUs (vCPU) – Approximately 32-64 vCPUs. This range is based on the need for high processing power for data analytics, graph processing, and machine learning tasks associated with large-scale knowledge graphs. 
Memory – Around 128GB to 256GB of RAM. This amount supports the processing of large datasets and complex algorithms without performance issues.
Disk Space – Minimum 5TB of disk space. This estimate accounts for the initial dataset sizes, intermediate processing data, and room for growth as the project scales.

**5.	Timeline:** 
The project will last for 3 years until 2027. 
 
**6.	Security and Compliance Requirements:** 
 
**7.	Approval:**

**Comment by arpita0911patel** [comment]
@jgong-ua - closing this ticket for now, please reopen or create a new one when this setup is needed.
