### ISSUE TITLE
HPC request for a CIROH-funded project

### ISSUE THREAD

**Issue by CHL-UA** [CIROH-UA/NGIAB-CloudInfra#131]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
Hamed Moftakhari
hmoftakhari@ua.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

This request is related to the "CIROH: Coastal Nature Based Solutions to Mitigate Flood Impacts and Enhance Resilience". To achieve the proposed objectives of the project to quantify the performance of wetland restoration projects through integrated field, remote sensing, and modeling-based studies we have proposed to develop a detailed hydrodynamics model of Mobile Bay, AL. This model will be further validated against in-situ observation and data collected at the field. The validated model will then be used to analyze the “what if” scenarios proposed based on objectives of the project.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.
N/A

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

Subject to change:

      GPU: 4xV100

      CPU: 30 cores

      Memory: 100 GB RAM

      Disk Space: 200 GB HD

**Options:**
1. HPC or VM
  
2. vCPU

3. Memory

4. Disk Space

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.

March through August 2024.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
N/A
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

N/A

**Comment by arpita0911patel** [comment]
Access is provided to Javier Camacho for this on Pantarhei by Trupesh.

**Comment by jameshalgren** [comment]
@TrupeshKumarPatel 
@javierroblescamacho
Working together on an individual application at Explore level for NSF Access credits to use on JetStream (or other resources): 
https://allocations.access-ci.org/opportunities/532287/requests/new
https://allocations.access-ci.org/project-types

Needs a 1-page project description, simple statement of CIROH affiliation, and CV (also CV from any Co-PI.)
