### ISSUE TITLE
Summer Institute Machine Learning Hydrology on-premise resource request

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB-CloudInfra#132]
@jmframe -- please populate this with pertinent information related to resources you expect to need over the summer.

**Comment by jmframe** [comment]
# 1.	Requester Information:
 This should include the name and contact information of the person making the request.
Jonathan M. Frame
Phone: (***) ***-****
Email: ******@******.com

# 2.	Project Information:
 Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.

## **Two projects:**

### **Project 1:** Summer Institute 2024 Geostationary Satellite data assimilation for NextGen.
**Description:** This project will seek to include live information from the NOAA GOES satellite mission into NextGen.
**Start date:** April 1st 2024
**End date:** December 31st 2024
**Team:** Jonathan Frame + four summer institute fellows

### **Project 2:** CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen. 
**Description:** This project will integrate and test deep learning (DL) and physics-informed deep learning (PIML) streamflow models and data assimilation into NextGen.
**Start date:** April 1st 2024
**End date:** December 31st 2025
**Team:** Jonathan Frame, Nels Frazier, Zach Wills + one tbd project scientist

# 3. Project Description:
 If your project involves developing software or scripts, briefly describe the software you plan to develop.

## **Project 1 and Project 2**:

**Platform:** Both of these projects should be done with the PantaRhei compute cluster. 

**Software:** Python, C++, Java, Anaconda, BLAS, Torch, NextGen, NGIAB, TensorFlow, Pytorch, Jupyter Notebooks, Git, HDF5, Zarr, Docker, Dask, GDAL, R, Earth Engine API

**Tasks and workflows:** Data collection and ingestion, computational modeling, machine learning, geospatial data processing and analysis, data visualization, data assimilation, calibration, model development, Real-time Data Integration, Parallel computing, cloud compute interfacing.

**Software:** Python, C++, Java, Anaconda, Torch, NextGen

# 4.	Resource Requirements:

 Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

## **Project 1:** Summer Institute 2024 Geostationary Satellite data assimilation for NextGen.

Disc space: This project will need to store more than 1TB or data. These data will be removed towards the end of the project.
GPU: This project will require some use of the GPUs. Likely, several hundreds or thousands of GPU hours. We will be training operational-ready models for NextGen.
vCPU: This project will require heavy use of the CPUs. Mostly for data processing.

## **Project 2:** CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen. 

Disc space: This project will need access to Atmospheric Forcing data that covers the entire U.S., and spans several decades. This could end up being several TB worth of data. But, these data should be useful for other CIROH projects as well. We would like to work closely with AWI and other CIROH projects to make sure that when we store data on the machine, it will be useful for others.
GPU: This project will require heavy use of the GPUs. Likely, several hundreds or thousands of GPU hours. We will be training operational-ready models for NextGen.
vCPU: This project will require heavy use of the CPUs. Mostly for data processing.


# 5.	Timeline:
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.

## **Project 1:** Summer Institute 2024 Geostationary Satellite data assimilation for NextGen.

The compute resources will be concentrated in late June 2024 through July 2024

## **Project 2:** CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen. 

This project will span from 2024 through 2025. We will work with AWI and other CIROH projects to make sure we are not hogging the machine.

# 6.	Security and Compliance Requirements:
 If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.

## **Project 1:**Summer Institute 2024 Geostationary Satellite data assimilation for NextGen.

N/A

## **Project 2:**CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen. 

N/A

# 7.	Approval:

 Indicate the necessary approval processes or sign-offs required for the request.

## **Project 1:**Summer Institute 2024 Geostationary Satellite data assimilation for NextGen.

Unknown

## **Project 2:**CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen. 

Unknown

**Comment by arpita0911patel** [comment]
@jmframe if you could please create a separate ticket for each project that would be great. Once created will close this ticket.

**Comment by arpita0911patel** [comment]
Please use this link for more details - https://docs.ciroh.org/docs/services/access#on-premises

**Comment by arpita0911patel** [comment]
https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/148 an https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/147 are created seperately to track this Summer Institute projects so closing this ticket.
