### ISSUE TITLE
Add validating output directory in docker image test

### ISSUE THREAD

**Issue by benlee0423** [CIROH-UA/NGIAB-CloudInfra#139]
Short description explaining the high-level reason for the new issue.

## Current behavior
During docker build and test, it does not validate outputs directory whether there is output file.

## Expected behavior
At the end of docker image test, it validate outputs directory by running the following commands.
```
ls "$HOST_DATA_PATH/outputs" | wc -l
```

**Comment by arpita0911patel** [comment]
This is fixed.
