### ISSUE TITLE
Fix input file directory path in x86 build and test action

### ISSUE THREAD

**Issue by benlee0423** [CIROH-UA/NGIAB-CloudInfra#140]
Short description explaining the high-level reason for the new issue.

## Current behavior
The input file in the Runner is old, and point to wrong directory.

## Expected behavior
The build and test action runs without any error.

## Steps to fix the issue
1. Download 004 input file in the Runner, and untar
2. Modify input file location in the action.yml in build and test
3. Verify the fix by running the action.

**Comment by arpita0911patel** [comment]
@benlee0423 we are good to cloes this now right since new latest-x86 is built and works fine with AWI-006?

**Comment by benlee0423** [comment]
@arpita0911patel We have to use 006 file both in arm64 and x86 build test. I will modify it.
