### ISSUE TITLE
Advancing cappabilities for NextGen (cloud)

### ISSUE THREAD

**Issue by martynpclark** [CIROH-UA/NGIAB-CloudInfra#144]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Martyn Clark

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

Developing capabilities to simulate hydrologic processes across North America using the nextGen framework

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

The project includes models developed in fortran -- summa and mizuRoute

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

2500 core years of computing
100 TB of storage

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
 Would like to transition to CIROH resources as soon as is practical

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
None.

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

Unknown

**Comment by arpita0911patel** [comment]
Thank you, Martyn, for submitting your Infrastructure request ticket.

We can set up a subaccount for your project on AWS. However, please note that according to our current AWS guidelines outlined here: [AWS Best Practices](https://docs.ciroh.org/docs/policies/Infrastructure/AWS%20best%20Practices), the allowed limit for a subaccount is $500 per project per month.

Please confirm if you are comfortable with this limit to proceed, and we will be happy to proceed with setting up the subaccount for you promptly.

For on-premise requests, please complete the form available at the following link: [On-Premise Request Form](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/new?assignees=&labels=on-prem&projects=&template=onprem-request.md&title=).

**Comment by arpita0911patel** [comment]
Thank you Martyn for submitting on-premise request form. Closing this ticket for now as the request is above the allowed cloud limit for now but let us know if anything changes on your requirement side to use the cloud.
