### ISSUE TITLE
NextGen computing

### ISSUE THREAD

**Issue by martynpclark** [CIROH-UA/NGIAB-CloudInfra#145]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Martyn Clark

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

Advance capabilities in the NextGen framework

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

Advance the summa and mizuRoute models (fortran) for use in NextGen

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. HPC or VM
  
2. vCPU

3. Memory

4. Disk Space

2500 core years of compute and 100 TB storage

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
As soon as is practical

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
None
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

None

**Comment by arpita0911patel** [comment]
This is being discussed in the Slack channel named "nextgen-computing-usask."

**Comment by arpita0911patel** [comment]
Provided ACCESS Explore allocation.
