### ISSUE TITLE
Cloud Infrastructure Request for Ashtan Moore 

### ISSUE THREAD

**Issue by acmoore11** [CIROH-UA/NGIAB-CloudInfra#146]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
Name: Ashtan Moore
Cellphone: 205-712-1724
Campus Email: acmoore11@crimson.ua.edu
Project Supervisor: Dr. Mark Cheng - mmcheng@eng.ua.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*
- This project is for ECE 492 (Capstone Design). My team plans to utilize IoT (Internet of Things) for measuring, recording, and analyzing hydrological data enabling efficient data transmission through LoRaWAN, facilitating cloud-based access for research purposes. One of our deliverables that is required by our supervisor is to display and possibly do some configuration of our data on a website or app. 

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.
- First my team plan to make a website that will display the collected data from our sensors. If time permits, we would like to develop an app that displays the same data as well. 

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.
- Based on my research, we need an AWS with block storage and online migration options. Thus Amazon EBS and EC2 seem to be what we need. The data has to be transmitted through LoraWAN, as it is a requirement for our project. The sensors will be collecting data constantly and for now we plan to transmit data multiple times an hour to keep it as close to real time as possible. 

**Options:**
1. Cloud Provider: AWS/Azure/GCP - AWS (It's actually the only one I've researched. If you have a better suggestion, I'd love to hear it!)

2. Required Services in the Cloud:
   List of AWS Services
   ====================
- **EC2** ***** 
- S3 – public, private, requester pay, bucket name suggestion?
- **EBS (Amazon Elastic Block Store)** ***** 
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**3.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
- We are working on this project now through the end of Fall 2024 semester. 
 

**4.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

**5.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 
- The estimate I got from getting AWS and 5 EC2 instances was 83.58/month. I am unsure if this was configured in the best way though. I'd appreciate any assistance. I am also unsure about the number of instances. I was thinking we would need one per sensor we need constant data from. 
 
**6.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.
- Mark Cheng (mmcheng@eng.ua.edu) needs to state his approval to a team member or you.

**Comment by arpita0911patel** [comment]
Hi @acmoore11 , this form is specifically for "CIROH consortium members embarking on research projects utilizing the NextGen framework are invited to request access to the research cloud, encompassing services from AWS and/or Google Cloud". Please let us know how it relates to NextGen to proceed further with this request.

**Comment by benlee0423** [comment]
@acmoore11 
Your AWS Account has been created.
For security, you can slack me for accessing AWS with credentials.

**Comment by acmoore11** [comment]
@benlee0423 How do I join your workspace to message you on slack?

**Comment by arpita0911patel** [comment]
@acmoore11 , I just sent you the slack invite at [acmoore11@crimson.ua.edu](mailto:acmoore11@crimson.ua.edu)

**Comment by benlee0423** [comment]
@arpita0911patel 
Can I revoke Ashtan's AWS access?
