### ISSUE TITLE
2024 Summer Institute project: Geostationary Satellite assimilation for NextGen

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#147]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Jonathan Frame

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

This project will seek to include near-real-time information from the NOAA GOES satellite mission into NextGen. 

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

Software: Python, C++, Java, Anaconda, BLAS, Torch, NextGen, NGIAB, TensorFlow, Pytorch, Jupyter Notebooks, Git, HDF5, Zarr, Docker, Dask, GDAL, R, Earth Engine API

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. HPC or VM

Platform: Project should be done with the PantaRhei compute cluster.  

3. vCPU

This project will require heavy use of the CPUs. Mostly for data processing. This project will require some use of the GPUs. Likely, several hundreds or thousands of GPU hours. We will be training operational-ready models for NextGen.

4. Memory

Minimum of 32GB of RAM per node, GPUs with at least 12GB of VRAM

6. Disk Space

This project will need to store more than 2TB or data. These data will be removed towards the end of the project.

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
The compute resources will be concentrated in late June 2024 through July 2024, but may extent into Fall and Winter 2024

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
N/A
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

Unknown

**Comment by arpita0911patel** [comment]
Access is granted.
