### ISSUE TITLE
CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen.

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#148]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Jonathan Frame

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

CIROH FY22 Deep Learning Modeling and Data Assimilation Capabilities for Nextgen.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

This project will integrate and test deep learning (DL) and physics-informed deep learning (PIML) streamflow models and data assimilation into NextGen.

Estimated software requirements: Python, C++, Java, Anaconda, BLAS, Torch, NextGen, NGIAB, TensorFlow, Pytorch, Jupyter Notebooks, Git, HDF5, Zarr, Docker, Dask, GDAL, R, Earth Engine API

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. HPC or VM
  
Project should be done with the PantaRhei compute cluster.

2. vCPU

This project will require heavy use of the CPUs. Mostly for data processing.

4. Memory

Minimum 32GB of RAM per node, GPUs with at least 12GB of VRAM

5. Disk Space

This project will need access to Atmospheric Forcing data that covers the entire U.S., and spans several decades. This could end up being several TB worth of data. But, these data should be useful for other CIROH projects as well. We would like to work closely with AWI and other CIROH projects to make sure that when we store data on the machine, it will be useful for others.

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
This project will span from 2024 through 2025. We will work with AWI and other CIROH projects to make sure we are not hogging the machine.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
N/A
 
**7.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

Unknown

**Comment by jmframe** [comment]
Hi @TrupeshKumarPatel. I need to start on this project as soon as possible. I need access to PantaRhei for this project. Do you have an estimated timeline for when I can get an account?

**Comment by TrupeshKumarPatel** [comment]
Hello @jmframe,
Could you please provide the following details here or over the [email](mailto:trpatel2@crimson.ua.edu?cc=apatel54@ua.edu,jshalgren@ua.edu,pvbangalore@ua.edu&subject=Pantarhei%20Account%20Creation%20Request) :
> [!NOTE]  
> 1.  PI's `Full Name`
> 2. PI's `Affiliated Institute`
> 3. PI's `Affiliated Email Address`
> 4. List of students who will need access, also please provide the following details of each student
>       * `Full Name` of student
>       * `GitHub User Name` of student
>       * `Affiliated Email Address` of student

**Comment by jmframe** [comment]
Hi Trupesh.

I will be working on the project through Lynker, as a subaward to Andy Wood
at the Colorado School of Mines. No students are planned to work on this
project, at the moment, but that may change down the line. Below is the
information you requested. And below that is my information.

   1. PI's Full Name: Andy Wood
   2. PI's Affiliated Institute: Colorado School of Mines
   3. PI's Affiliated Email Address: ***@***.***
   4. List of students who will need access, also please provide the
   following details of each student
      - Full Name of student: N/A
      - GitHub User Name of student: N/A
      - Affiliated Email Address of student: N/A

*Subaward PI and technical developer for the project:*
Name: Jonathan Frame
Affiliated Institute: Lynker (as subaward from Colorado School of Mines)
Affiliated Email Address: ***@***.***
Affiliated University of Alabama BAMA ID: jmframe
GitHub Username: jmframe
Affiliated University of Alabama email: ***@***.***
Affiliated University of Alabama Campus Wide ID: 11928921

**Comment by jmframe** [comment]
I am able to access the cluster. Thank you very much!
