### ISSUE TITLE
Tethys Application to interact with the NWM google public NWM dataset using Google Big Query 

### ISSUE THREAD

**Issue by romer8** [CIROH-UA/NGIAB-CloudInfra#152]
**1.    Requester Information:**
Giovanni Romero from (Aquaveo) gromero@aquaveo.com

**2.    Project Information:** 
The google cloud credits are going to be used to develop a Tethys application  that will be used with the NWM big query public dataset. The aim of the application is to show users how to integrate NWM public dataset with the Tethys platform using big query.

**3.  Project Description:**
The github repo for the application is here: https://github.com/Aquaveo/tethys-bigquery

**4.    Resource Requirements:** 
Each query to the NWM big query dataset consumes an amount of credit from google cloud. We would like to have an amount of credits taht can be sued to develop the tutorial (Tethys application) used in the CIROH dev conference

**Options:**
1. Cloud Provider:  GCP

2. Required Services in the Cloud:

Google BigQuery

**5.    Timeline:** 
The application needs to be finished by Jun 1, but in order to develop the application a good deadline might be April 30th, so the team have more than enough time to develop the application
 
**6.    Security and Compliance Requirements:** 
None

**7.    Estimation:** 
Estimation for some of the queries are as follow. The total amount is not the total that is being requested, but a total of what it would take to make one query to each of the tables in the NWM public dataset.

Analysis_assim_channel_rt - 14.84 TB - $84.36
analysis_assim_extend_channel_rt - 5.99 tb - $34.05
analysis_assim_extend_no_da_channel_rt - 5.57 tb - $31.66
analysis_assim_long_channel_rt - 10.32 tb - $58.66
analysis_assim_long_no_da_channel_rt - 9.21 tb - $52.35
analysis_assim_no_da_channel_rt - 14.4 tb - $81.86 
long_range_channel_rt - 312.89 tb - $1778.58
medium_range_channel_rt - 1.13 pb - $7,244.5
medium_range_no_da_channel_rt - 54.33 tb - $308.83 
short_range_channel_rt - 89.19 tb - $506.99
stream_network - 1.73 gb - $.01
Total - $10,181.85

**Comment by arpita0911patel** [comment]
@romer8 is it 10k per month?

**Comment by romer8** [comment]
the estimate is actually just the sum of one query to all the tables, so we are not sure how many queries we would like to allow the user to do in the app

**Comment by arpita0911patel** [comment]
@romer8 We are still waiting to get our CIROH Google Account. Once we have the process ready will let you know when we could give you access to Google services for your project. As per our discussion on call, please send the updated budget per month for this project.

**Comment by romer8** [comment]
@arpita0911patel,  thanks for your response.. We have discussed that we will be switching to the NWM API that uses big query. Thanks for your help!
