### ISSUE TITLE
Summer Institute compute resources PRE-request

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#153]
Hello,

I am providing information for several projects that will be requesting computational capacity for the summer institute. Each project will eventually make a specific request, but I wanted to provide this summary of the computational requirements of the Summer Institute as a whole. I'm hoping this can 1) Help AWI prepare for the individual project requests, and 2) identify common computational requirements that might be generally assigned to all SI students, which specific requirements reserved for each project. Can you please review this pre-request and inform us on any particular problems that might arise, and guide us on the best action for individual project requests. We do have our individual project information in the compute resources request template you've provided, and we can simply submit those, but there might be something important to consider beforehand. Please let me know if you'd like to discuss this.

**Common Platform Needs:**
- Platforms: Primarily Linux with some projects requiring Windows for specific applications (ArcGIS Pro, HEC-RAS).
- Common software requirements across projects include Python, R, GIS software (ArcGIS, QGIS), TensorFlow, PyTorch, Jupyter Notebooks, Git, Docker, Dask, GDAL, and specialized software for flood modeling and satellite data processing.

**Hardware and Storage Requirements:**
- Disc Space: All projects combined require significant storage capacity, each needing up to 1TB, cumulatively necessitating several terabytes of scalable and possibly shared storage to facilitate ease of access and data management.
- Memory: Requirements range from 32GB to 100GB per node, suggesting a need for high-memory nodes.
- GPUs: Varied requirements, from specific high VRAM GPUs for deep learning tasks to minimal GPU requirements for other projects. A mix of GPU-equipped and standard nodes may be optimal.
- vCPUs: A diverse range from intensive CPU usage in data processing and model training to moderate use in GIS and flood modeling tasks. 

**Special Requirements:**
- Virtual desktop infrastructure (VDI) for Windows-based applications, alongside traditional server access for Linux-based tasks.
- Integration capabilities with cloud compute resources for flexibility in resource allocation.

**Comment by arpita0911patel** [comment]
Thank you Jonathan for starting this thread and for our discussion on call today along with James and Trupesh.
As per our discussion, GIS workstation access James will be able to provide. Please reach out to him directly for that.

For AWS (new subaccount) , 2i2c (new user access, new software install request) and Pantarhei (VPN request , new user access or new software instal request), please use the forms available at:
https://docs.ciroh.org/docs/services/access

**Comment by arpita0911patel** [comment]
Closing this ticket as access is granted. Please reopen if anything.
