### ISSUE TITLE
ciroh-ngen-image tag change

### ISSUE THREAD

**Issue by JordanLaserGit** [CIROH-UA/NGIAB-CloudInfra#158]
In the awiciroh DockerHub, the x86 ngen image is tagged "ciroh-ngen-image:latest-x86". The arm image is tagged "ciroh-ngen-image:latest". Docker will detect the platform, so the "x86" in the x86 image is not needed and should be removed. This will make the tags consistent between the two platforms.

![Screenshot 2024-05-07 102431](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/79336055/d7a57849-0040-4888-93bf-a00fd890bba3)

**Comment by JordanLaserGit** [comment]
@arpita0911patel @ZacharyWills @benlee0423

**Comment by benlee0423** [comment]
@JordanLaserGit 
We still need both arm and x86 images, and they should be separately tagged based on the platform.

**Comment by JordanLaserGit** [comment]
I agree we need both images. It's my understanding that docker will pull which ever image based on the host's platform so the platform in the tag is not required.

**Comment by benlee0423** [comment]
@JordanLaserGit 
Thank you for suggestion.
Let's come back this discussion after DEVCon. We don't want to make any change at the last minutes.

**Comment by arpita0911patel** [comment]
https://github.com/CIROH-UA/NGIAB-CloudInfra/pull/229/files

**Comment by arpita0911patel** [comment]
@JordanLaserGit - closing this ticket based on https://github.com/CIROH-UA/NGIAB-CloudInfra/pull/229/files
Please open new one if anything.
