### ISSUE TITLE
Access request for CIROH Google Cloud Platform

### ISSUE THREAD

**Issue by horsburgh** [CIROH-UA/NGIAB-CloudInfra#162]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Jeff Horsburgh
- PI's Affiliated Institute: Utah State University
- PI's Affiliated Email Address: jeff.horsburgh@usu.edu

**Details**: We are requesting that the following individuals be given access to CIROH's Google Cloud Platform account:
Jeff Horsburgh: [jeff.horsburgh@usu.edu](mailto:jeff.horsburgh@usu.edu) (project Co-PI)
Sierra Young: [sierra.young@usu.edu](mailto:sierra.young@usu.edu) (project PI)
Sajan Neupane: [sajan.neupane@usu.edu](mailto:sajan.neupane@usu.edu) (project MS student)
Razin Issa: [razinbin.issa@usu.edu](mailto:razinbin.issa@usu.edu) (project MS student)
Safran Khan: [safran.khan@usu.edu](mailto:safran.khan@usu.edu) (project PhD student)

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

**Project Title**: CIROH: Advancing Camera-Based Monitoring for Operational Hydrologic Applications
**Project Summary**: [https://ciroh.ua.edu/research-projects/advancing-camera-based-monitoring-for-operational-hydrologic-applications/](https://ciroh.ua.edu/research-projects/advancing-camera-based-monitoring-for-operational-hydrologic-applications/)
**Project Goals**: The overall goal of this project is to demonstrate how operational requirements for integrating low-cost cameras and computing infrastructure into existing hydrologic monitoring networks can be met, along with evaluating the benefits of cameras for continuous monitoring and prediction.
**Project Benefits**: We seek to develop serverless cloud workflows/pipelines for processing imagery collected at stream gaging sites. Information extracted from images will provide realtime, hydrologically relevant information - e.g., stream width, depth, velocity to augment available data from realtime USGS streamflow gages and will make more data and information available at gage locations for use in NextGen modeling efforts. We are investigating serverless cloud as a means to achieve scalability for growing the number of locations from research scale (a handfull of sites with cameras) to operational scale with hundreds or even thousands of sites. Part of this work is examining advantages and tradeoffs of different cloud platforms. For that part of the work, we are starting with AWS (for which we already have access to CIROH's AWS account) and Google Cloud Platform (for which we are asking for access as part of this request). 

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

We will be developing lambda functions for AWS and equivalent Google Cloud Functions (for comparison) to automate the transfer, preprocessing, segmentation, and analysis of images collected using cameras at active stream gaging locations. Functions will execute machine learning models on the captured images to extract width, depth, and velocity. We plan to develop serverless cloud workflows/pipelines for processing imagery collected at stream gaging sites. Code will generally be written using Python, but will involve a variety of scripts designed to execute different parts of the image processing workflow (e.g., image capture on a datalogger, transfer to cloud storage, image preprocessing, model execution, results generation, and logging hydrologic variables to a data store). All of the code we develop will be hosted publicly in a GitHub repository. 

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**NOTE:** Our needs for this part of the project are similar to the earlier request we sent to get access to the CIROH AWS account. We just need to be able to develop equivalent functions/pipelines across the different platforms for comparison purposes and to examine the potential cost and performance tradeoffs.

**Options:**

1. Cloud Provider: GCP

2. Required Services in the Cloud:

**List of GCP services we anticipate needing**
- Google Cloud Storage
    - Each image we capture is about 2 MB based on current image resolution
    - Each 10 s video we capture is about XX MB based on current camera configuration
    - Image volume estimate: ~100 MB of image data per day per site. We have 3 installed sites and may deploy 1-2 more sites
    - Video volume estimate: ~600 MB of video data per day per site.
    - If storage size is an issue, we do not have to persistently store the image and video data forever. What to keep (videos and images) and for how long is part of our investigation
- Google Cloud Functions
    - Using Google Cloud Functions to do our image/video processing
    - Invoked to process each image/video, but could do bursts of images/videos (multiple processed at a time to reduce invocations)
- Dataflow
    - This may be interesting to investigate whether there is an application for our pipeline here.
- CloudBuild
- Google IAM (not sure about this one)
- Google Artifact Registry

**List of GCP Services we do not anticipate needing**
- Google Compute Engine
- Google Kubernetes Engine (GKE) - unsure about this one. Don't think we need it for now.
- Google VPC
- Google BigQuery
- Other: please list

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 
We anticipate using resources through the end of our project, which is a 3-year CIROH project funded starting June 1, 2023 and ending May 2026.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 
We don't currently have any specific security or compliance requirements for our development and testing. The image and video data we are collecting are not sensitive and have no restrictions on access or release. All of our source code and development is open, so no concerns there.

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

We anticipate that the image/video storage will be relatively inexpensive in Google Cloud Storage, and the rate of data collected is not overly frequent (e.g., one new image/video per site every 30 minutes). We will incur additional costs with executing Google Cloud Functions. Storage in the Google Artifact Registry may be in the free tier. We anticipate that overall costs should be in the ballpark of $100 - $150 per month.

**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

Please contact me with any questions

Jeff Horsburgh: jeff.horsburgh@usu.edu

**Comment by benlee0423** [comment]
USU-Hydrologic project was created.
@horsburgh You should get an invite to join the project.
The other 4 users were assigned to Viewer Role.
Let me know if any services you need access to.

**Comment by benlee0423** [comment]
@horsburgh 
We are wondering if all 5 users in the requests get invitation email to join the project.
If not, can we ask them to associate *.usu email accounts to google?

**Comment by arpita0911patel** [comment]
Closing this ticket based on email from Jeff as he is able to access the account now.
