### ISSUE TITLE
On-Premises Infrastructure Request - UIOWA

### ISSUE THREAD

**Issue by muhammedyusuf-sermet** [CIROH-UA/NGIAB-CloudInfra#164]
**1.	Requester Information:**
- PI's Full Name: Ibrahim Demir
- PI's Affiliated Institute: University of Iowa
- PI's Affiliated Email Address: ibrahim-demir@uiowa.edu

**2.	Project Information:** 
Our project aims to leverage advanced AI and multimodal models to enhance the research, education, and operation capabilities for stakeholders of the hydrological domain. We will be conducting research on perception-language tasks, multimodal dialogue, image captioning, visual question answering, and long-term conversation memory. The project will handle a variety of modalities such as raster images, videos, 3D scenes and animations, and maps. The cloud credits will significantly support the research, testing, and fine-tuning of our AI models, contributing to the shared infrastructure by providing advanced analytics capabilities and enriching hydrological research.

**3.  Project Description:**
We plan to develop software that uses AI models like Multimodal-GPT, LLama-v3, and Command R+ as well as to fine-tune and train the feasible models in a domain and purpose-specific manner. The software will be used to analyze, process, and interpret hydrological data, aiding in the development of more effective and efficient hydrological solutions.

**4.	Resource Requirements:** 
We would like request access to use the GPU Node of Pantarhei (v100).

**5.	Timeline:** 
We would like to start the training and testing process immediately.

**6.	Security and Compliance Requirements:** 
The project will adhere to the University of Iowa's security and compliance guidelines, including ensuring that any sensitive data is securely stored and transported.
 
**7.	Approval:** 
Please contact PI Ibrahim Demir (@demiribr) for questions.

**Comment by arpita0911patel** [comment]
@TrupeshKumarPatel - please let us know the latest on this request.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Yusuf Sermet (@muhammedyusuf-sermet).

**Comment by arpita0911patel** [comment]
Closing this ticket as access is granted. Please reopen if anything.
