### ISSUE TITLE
Summer Institute project compute resource request: identify high flow thresholds - GIS

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#165]
**Description**: 

Identification, compilation, and dissemination of hydrologic/hydrodynamic attributes from multi-source, open-access observational flood database 

Location: Houston TX (+ other locations)
Event: Hurricane Harvey (+ other recent events)
Provided Datasets: Time-series of flood inundation, Examples of open source observational data (e.g., satellite imagery, media photos, drones, post-event flood studies, etc.)

Hazard: High water marks (location), 
Spatial information: Satellite image, 
Impact/Risk:
Urban flood datasets: 

**Start date**: May 2024

**End date**: December 2024

**Team**: Kelsey McDonough, Sanjib Sharma and Summer Institute Fellows

**Platform**: Linux and Windows

**Software**: GIS (ArcGIS pr QGIS), Google Earth Engine, GitHub, Python, R

**Datasets**: Satellite images, high-water marks, traffic camera images, crowdsourced media, NFIP FIRMs, NOAA storm events database, observational stream gauge data, etc.
Tasks and workflows: High-resolution data-model integration, model diagnostics, and predictive skill evaluation using multi-source flood data. 

**Disc space**: 1 TB

**Memory**: 100 GB

**GPU**: Depends upon the selected model and data products. 

**vCPU**: This project will heavily rely on CPU.

**Timeline**: May 2024 – December 2024

**Security and Compliance Requirements**: NA

**additional project description**:
Operational and research efforts are focused on providing flood forecasts with greater accuracy, higher spatiotemporal resolution, and improved uncertainty quantification. However, accurate and reliable flood prediction still remains a unique challenge due to the lack of open-source flood hazards and risk datasets. Many sources of flood datasets come with restrictions on data sharing, and hence the datasets are not accessible to the public or research communities. In addition, we are currently underutilizing various flood information sources that could be used for model calibration, forecast verification, and risk analysis. Last, but not least, individual datasets have their own limitations, and no single database can comprehensively describe spatiotemporal dynamics of flooding.

We will address this challenge by developing methods to (i) identify types of open-source observational flood data, (ii) compile data into a unified, consistent database, (iii) extract different hydrologic/hydrodynamic attributes, and (iv) disseminate open-access data for future research and operational applications. 

Key Questions:
What are the available open source observational flood data for better spatiotemporal characterization of flooding?
How do you compile and/or present a unified, consistent database? 
What insights can you get from the data? What are the different hydrologic/hydrodynamic attributes associated with each type of observational flood data and how can it be extracted?
How do you disseminate for future research applications? (e.g., Github, Hydroshare,..)

**Comment by ciroh-it-admin** [comment]
@sepehrkrz - Sepehr will provide access to GIS workstation for ArcGIS and QGIS.

For Google Earth Engine - Please use 2i2c JupyterHub (Data Workflow 101 image).

**Comment by arpita0911patel** [comment]
Please provide UA username for getting access to GIS workstation.
