### ISSUE TITLE
Summer Institute project compute resource request: FIM Uncertainty Analysis - GIS

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#166]
**Description**: 
quantification of the sources of uncertainty in OWP HAND-FIM prediction
 
**Start date**: May 2024

**End date**: Dec 2024

**Team**: Xingong Li and Sagy Cohen

**Platform**: Linux, Windows

**Software**: ArcGIS Pro, OWP HAND-FIM, LisFlood-FP, HEC-RAS, MATLAB (part of FLDPLN), FLDPLN Python packages, VSC.

**Tasks and workflows**: The users will need to run some Windows applications (primarily ArcGIS Pro and HEC-RAS 2D) so a virtual desktop approach will be needed. Other, Linux-based models could be run on a server though a virtual desktop environment may be useful.

**Disc space**: Likely under 1 TB.

**Memory**: 32-64 GB 

**GPU**: Unlikely to need (except for VM needs)

**vCPU**: 20 should be enough
Timeline: Be good to enable till after AGU (end of 2024).
Security and Compliance Requirements: N/A

**additional project description**: 
The NOAA Office of Water Predictions (OWP) developed an operational Flood Inundation Mapping (FIM) forecasting framework based on the Height Above Nearest Drainage (HAND) methodology. The application of the methodology requires a conversion of streamflow predictions (e.g. from the National Water Model (NWM)) to stage using an approach called Synthetic Rating Curves (SRC). The OWP HAND-FIM version 4 was demonstrated to have greater accuracy than the previous versions. Recently an adjustment factor was introduced to the SRC to improve FIM predictions. Large-scale evaluation of the OWP HAND-FIM is mostly based on design flood events (100 and 500-year floods) against Base Level Engineering (HEC-RAS) simulations. Sources of uncertainties in the OWP HAND-FIM predictions include biases in the NWM streamflow forecast, channel bathymetry, roughness coefficient (Manning’s n - used in the SRC calculation), small-scale features in the landscape, and evaluation benchmark and approach. 
Approaches for the quantification of the sources of uncertainty in OWP HAND-FIM prediction can take many forms, depending on the potential element investigated. Comparison of the OWP HAND-FIM prediction skills against those of more complex FIM solvers (e.g. FLDPLN, AutoRoute, Lisflood-FP, HEC-RAS) can provide a nuanced understanding of the sources and settings contributing to prediction biases. In addition, an intercomparison of multiple models, at a range of complexities and settings, can provide useful insights into systematic limitations/advantages of specific solvers. This can help inform future development of operational FIM that may involve a more flexible framework. 

Tentative ideas for studying FIM uncertainty (or error):
Modeled mechanisms/processes (for example, backfill vs spillover flooding)
Model inter-comparison (same inputs with different models, focus on HAND and FLDPLN?)
3 Kansas sites + Sagy’s 2 sites (NC & Arkansas)
Streamflow predictions
Comparison of FIM predictions using (NWM) predicted and (gage) observed streamflow.
Comparison of FIM predictions using NWM+SRC water level against (gage) stage observations.
DEM
Same model with different DEMs
Quality (e.g. 3DEP vs NED)
Resolution
Hydro-conditioning method and workflow
Flood defense data
Discharge to stage conversion (i.e. Rating Curves)
Same model with different discharge-stage methods
Adjustment factor for HAND-derived SRC
FLDPLN-based SRC
Discharge uncertainty (and how it’s compared with SRC uncertainty)
Evaluation benchmark and approach
Ground truth data and metrics
Remote sensing flood extent
Evaluation approach and metrics

**Comment by ciroh-it-admin** [comment]
Sepehr will provide access to GIS workstation for this request. Please let us know if anything else is needed.

**Comment by arpita0911patel** [comment]
Please provide UA username for getting access to GIS workstation.
