### ISSUE TITLE
006 Input file getting tar ignoring message

### ISSUE THREAD

**Issue by benlee0423** [CIROH-UA/NGIAB-CloudInfra#173]
Short description explaining the high-level reason for the new issue.

## Current behavior
$ tar -xf AWI_16_2853886_006.tar.gz 
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'
tar: Ignoring unknown extended header keyword 'SCHILY.fflags'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.com.apple.FinderInfo'

## Steps to replicate behavior (include URLs)

1. wget --no-parent https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-006/AWI_16_2853886_006.tar.gz
2. tar -xf AWI_16_2853886_006.tar.gz

**Comment by arpita0911patel** [comment]
@benlee0423 where do you see this error? I do not see it on my mac.

**Comment by benlee0423** [comment]
@arpita0911patel 
If you create tar.gz package in Mac, probably that's the reason.
This warn message happens in linux machine. We want to create tar.gz package in linux, it was documented [here](https://github.com/CIROH-UA/NGIAB-CloudInfra/wiki/Creating-tar.gz-file).
This is not deal breaker, and we can fix after devcon.

**Comment by benlee0423** [comment]
Fixed.
