### ISSUE TITLE
Access for Summer Institute - GIS

### ISSUE THREAD

**Issue by XingongLi** [CIROH-UA/NGIAB-CloudInfra#181]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Xingong Li
- PI's Affiliated Institute: University of Kansas
- PI's Affiliated Email Address: lixi@ku.edu

**2.	Project Information:** 
The access is for the Summer Institute at UA. 

**3.  Project Description:**
Project will be focusing on flood inundation mapping.

**4.	Resource Requirements:** 
Platform: Linux, Windows
Software: ArcGIS Pro, OWP HAND-FIM, LisFlood-FP, HEC-RAS, MATLAB (part of FLDPLN), FLDPLN Python packages, VSC.
Tasks and workflows: The users will need to run some Windows applications (primarily ArcGIS Pro and HEC-RAS 2D) so a virtual desktop approach will be needed. Other, Linux-based models could be run on a server though a virtual desktop environment may be useful.
Disc space: Likely under 1 TB.
Memory: >=64 GB 
GPU: Unlikely to need (except for VM needs)
vCPU: 20 should be enough

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5.	Timeline:** 
The SI officially starts on June 10 and ends July 26. However, I would like to test it next week and SI students may need to continue to access it to prepare their projects for publication. So, I would like to request the access from June 3 to the end of 2024. 

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Please provide UA username for getting access to GIS workstation.

**Comment by XingongLi** [comment]
I don't have a UA username. I'm the theme leader for the Summer Institute. Thanks, Xingong

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sepehrkrz** [comment]
Summer institute request access has been successfully implemented. Closing Issue
