### ISSUE TITLE
Bug with visualization

### ISSUE THREAD

**Issue by MIsmlAhmed** [CIROH-UA/NGIAB-CloudInfra#182]
When running the NGIAB, it runs fine until the visualization step, specifically, the following part:

     Select an option (type a number): 
     1) Run GeoServer using existing local docker image
     2) Run GeoServer after updating to latest docker image
     3) Exit

When trying to use option `2`, the script pulls the latest GeoServer docker image but fails to launch it. When I re-run the NGIAB and use option `1` to use the existing GeoServer docker image, it continues and visualizes the output successfully.

**Comment by arpita0911patel** [comment]
@romer8 - pls take a look.

**Comment by romer8** [comment]
@MIsmlAhmed thanks for opening an issue I will try to solve the issue this week.

**Comment by romer8** [comment]
@MIsmlAhmed I have tried to reproduce the error, but I have not been able to reproduce it. Can you share the following, so I can have a better idea of the bug:

- Screenshot of the error
- Operating system in which you are running the script.
- Can you also run the `./viewOnTethys.sh` I would like to see if the error shows also here.

**Comment by arpita0911patel** [comment]
@MIsmlAhmed let us know if this is still an issue on your end.

**Comment by MIsmlAhmed** [comment]
It is now working fine. I think I might have done something wrong back then when I got this error.
