### ISSUE TITLE
Jackson Edwards - Summer Institute Cloud Infrastructure Request Form - 2i2c

### ISSUE THREAD

**Issue by jackhazard00** [CIROH-UA/NGIAB-CloudInfra#184]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

- Requester Name: Jackson Edwards
- Requester Institution: University of Kansas
- Requester email address: j375e293@ku.edu

- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: Lynker
- PI's Affiliated Email Address: jframe@lynker.com

**2.    Project Information:**
Summer Institute Bootcamp, 2024. The bootcamp will include training on basic computational skills, and this will be done on the AWI 2i2c resource. All bootcamp participants will need access to this cloud compute platform.

**3.  Project Description:**
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

**4.    Resource Requirements:**
We can use mostly the same 2i2c compute environments that were set up for the CIROH DevCon.

**5.    Timeline:**
June 10th - July 25th
 
**6.    Security and Compliance Requirements:**
N/A
 
**7.    Estimation:**
Unknown
  
**8.    Approval:**
Unknown

**Comment by arpita0911patel** [comment]
@jackhazard00  - To request access for the 2i2c JupyterHub, please use the following form: https://docs.ciroh.org/docs/services/cloudservices/ciroh%20jupyterhub/#-jupyterhub-2i2c-infrastructure-request-form

Each user should submit a separate form, as access is granted based on their GitHub username.

We will retain the images generated for DevCon24 in the production 2i2c JupyterHub for your convenience.

Thank you,
Arpita

**Comment by manjilasingh** [comment]
@jackhazard00 - You now have access to 2i2c JupyterHub
