### ISSUE TITLE
[SI 2024 fellow] Thanh Nhan Duc Tran - 2i2c

### ISSUE THREAD

**Issue by ductran27** [CIROH-UA/NGIAB-CloudInfra#185]
**1.	Requester Information:**
- Requester Name: Thanh Nhan Duc Tran (Duc Tran)
- Requester Institution: University of Virginia
- Requester email address: syu3cs@virginia.edu

This should include the name and contact information of the person making the request.
- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: Lynker
- PI's Affiliated Email Address: jframe@lynker.com

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*
Summer Institute Bootcamp, 2024. The bootcamp will include training on basic computational skills, and this will be done on the AWI 2i2c resource. All bootcamp participants will need access to this cloud compute platform.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.
We can use mostly the same 2i2c compute environments that were set up for the CIROH DevCon.

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
June 10th - July 25th

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
N/A

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/
Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
Unknown

**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.
Unknown

**Comment by arpita0911patel** [comment]
@ductran27 - To request access for the 2i2c JupyterHub, please use the following form: https://docs.ciroh.org/docs/services/cloudservices/ciroh%20jupyterhub/#-jupyterhub-2i2c-infrastructure-request-form

We will retain the images generated for DevCon24 in the production 2i2c JupyterHub for your convenience.

Thank you,
Arpita

**Comment by manjilasingh** [comment]
@ductran27 - You now have access to 2i2c JupyterHub
