### ISSUE TITLE
Summer Institute Bootcamp, 2024 - 2i2c

### ISSUE THREAD

**Issue by He1a1eh** [CIROH-UA/NGIAB-CloudInfra#186]
**1.    Requester Information:**
- Requester Name: Helaleh Khoshkam
- Requester Institution: University of Hawaii at Manoa
- Requester email address: helaleh@hawaii.edu

- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: Lynker
- PI's Affiliated Email Address: [jframe@lynker.com](mailto:jframe@lynker.com)

**2.    Project Information:**
Summer Institute Bootcamp, 2024. The bootcamp will include training on basic computational skills, and this will be done on the AWI 2i2c resource. All bootcamp participants will need access to this cloud compute platform.

**3.  Project Description:**
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

**4.    Resource Requirements:**
We can use mostly the same 2i2c compute environments that were set up for the CIROH DevCon.

**5.    Timeline:**
June 10th - July 25th
 
**6.    Security and Compliance Requirements:**
N/A
 
**7.    Estimation:**
Unknown
  
**8.    Approval:**
Unknown

**Comment by manjilasingh** [comment]
@He1a1eh - You now have access to 2i2c JupyterHub

**Comment by He1a1eh** [comment]
Thank you, Manjila!

Best,
Helaleh
