### ISSUE TITLE
Requesting a virtual GPU access

### ISSUE THREAD

**Issue by supathdhitalGEO** [CIROH-UA/NGIAB-CloudInfra#190]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Prof. Dr. Sagy Cohen
- PI's Affiliated Institute: University of Alabama, Tuscaloosa
- PI's Affiliated Email Address: scohen@ua.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*
- I am doing surrogate flood modeling task using deep learning approach. It includes high dimensional image data so the computational power is required a bit more than it expected. Thus I need the access of Jupyterhub  or any other virtual medium of GPU access to train my model. This GPU access will help me to efficiently train the model. 

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.
- It a deep learning model. 

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.
- my dataset are high dimensional raster images so as possible as I need maximum GPU access. If possible provide me Huge - 52GB RAM, 16 CPUs access, if not please stick with atleast Large one. 

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 - I started the masters degree in UA in spring 2024. So I will be here for next 1 and  half years. That's why can you do it for next 1 year atleast and if I need more then I will request again.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 - Not specific one

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.
Ok.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Supath Dhital (@supathdhitalGEO).

**Comment by supathdhitalGEO** [comment]
Thank You.
