### ISSUE TITLE
Summer Internship Bootcamp - Access Request Form - Janani Kandasamy 2i2c

### ISSUE THREAD

**Issue by JananiKandsamy** [CIROH-UA/NGIAB-CloudInfra#191]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- Requester Name: Janani Kandasamy
- Requester Institution: George Mason University
- Requester email address: jkandasa@gmu.edu

- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: Lynker
- PI's Affiliated Email Address: jframe@lynker.com

**2.    Project Information:**
Summer Institute Bootcamp, 2024. The bootcamp will include training on basic computational skills, and this will be done on the AWI 2i2c resource. All bootcamp participants will need access to this cloud compute platform.

**3.  Project Description:**
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

**4.    Resource Requirements:**
We can use mostly the same 2i2c compute environments that were set up for the CIROH DevCon.

**5.    Timeline:**
June 10th - July 25th
 
**6.    Security and Compliance Requirements:**
N/A
 
**7.    Estimation:**
Unknown
  
**8.    Approval:**
Unknown

**Comment by benlee0423** [comment]
@JananiKandsamy 
To request access for the 2i2c JupyterHub, please use the following form: https://docs.ciroh.org/docs/services/cloudservices/ciroh%20jupyterhub/#-jupyterhub-2i2c-infrastructure-request-form

Thank you,
Ben

**Comment by manjilasingh** [comment]
@JananiKandsamy - You now have access to 2i2c JupyterHub
