### ISSUE TITLE
Fix recent NextGen builds

### ISSUE THREAD

**Issue by JordanLaserGit** [CIROH-UA/NGIAB-CloudInfra#193]
NGIAB is currently suffering from the issue described here: https://github.com/NOAA-OWP/ngen/issues/834
This is causing NGIAB runs to fail sporadically. Looks like we will need to rebuild the images.

**Comment by JordanLaserGit** [comment]
@arpita0911patel @benlee0423

**Comment by benlee0423** [comment]
@JordanLaserGit
Will take a look.

**Comment by JordanLaserGit** [comment]
@hellkite500 said what I'm seeing is not related to this issue as it should only effect builds made yesterday. Will do more testing to try and find the cause of the behavior I'm seeing with NGIAB.
