### ISSUE TITLE
UA SGPI REU: Artificial Intelligence for Water Forecasting

### ISSUE THREAD

**Issue by aarm1978** [CIROH-UA/NGIAB-CloudInfra#194]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: **Dr. Steven Burian**
- PI's Affiliated Institute: The University of Alabama / Alabama Water Institute
- PI's Affiliated Email Address: sburian@ua.edu

**2.	Project Information:** 
The **UA SGPI REU: Artificial Intelligence for Water Forecasting** program aims to research and develop new computational tools for predicting floods, droughts, and water quality. This project will leverage the on-premises infrastructure to process large datasets, perform complex simulations, and create advanced machine learning models. The outcomes will contribute to the broader research community by enhancing the understanding of water systems under climate change and developing open-source tools for water prediction.

**3.  Project Description:**
The project involves developing machine learning algorithms and process-based models to predict hydrologic phenomena such as streamflow, floods, and droughts. The software development will focus on data preprocessing, model training, and deployment, utilizing big data analytics and visualization techniques to support water resources management and decision-making processes.

**4.	Resource Requirements:** 
High-Performance Computing (HPC) resources are essential for efficiently processing and analyzing the large datasets involved in this project. The requirements are as follows:

- **Virtual CPUs (vCPU)**: Approximately 64-128 vCPUs, needed for high processing power to run data analytics, simulations, and machine learning models.
- **Memory**: Around 256GB to 384GB of RAM, sufficient for handling large-scale simulations and complex data processing tasks.
- **Disk Space**: Minimum 500GB of disk space to store initial datasets, intermediate processing data, and provide room for growth as the project scales.
- **GPU Nodes**: Utilization of nodes with NVIDIA Tesla V100 GPUs for training deep learning models and performing accelerated computing tasks.

**5.	Timeline:** 
The REU program specifically associated with this request will finish 1 August 2024. However, the research team supporting the REU will continue experiments through the remaining months of 2024 and into 2025 to prepare for another REU season. We expect the summer usage will be more intense, but would like to request access to the resource continuously from June 2024 through August 2027, to accommodate this and the next three REU cycles.

**6.	Security and Compliance Requirements:** 
The project will adhere to the University of Alabama's data security policies and ensure compliance with relevant data protection regulations.

**7.	Estimation:** 
no cost (all on-prem resources) 

**8.	Approval:** 

*Side note:* Great notes about style and usage for "on-premise" vs. "on premises" [here](https://www.govloop.com/on-premise-vs-on-premises-the-debate-and-resolution/)...

**Comment by benlee0423** [comment]
@TrupeshKumarPatel

**Comment by jameshalgren** [comment]
@TrupeshKumarPatel -- we submitted a user access request form ahead of creating this ticket. The primary user of interest here is the issue submitter (See https://dev.azure.com/ciroh-it-admin/Infrastructure-CIROH-UA/_workitems/edit/938/)
But we will have a few additional students and will link those requests directly to this GH issue.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Andres Ramirez Molina (@aarm1978).

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Quinn Lee.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Hudson Markin.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Troy Marks.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Yehang Rai.
