### ISSUE TITLE
Summer Institute New Pantarhei & HPC  User 

### ISSUE THREAD

**Issue by hgholizadeh7** [CIROH-UA/NGIAB-CloudInfra#195]
**1.    Requester Information:**
- Requester Name: Hossein Gholizadeh
- Requester Institution: The University of Alabama
- Requester email address:  hgholizadeh@crimson.ua.edu

- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: Lynker
- PI's Affiliated Email Address: [jframe@lynker.com](mailto:jframe@lynker.com)

**2.	Project Information:** 
Summer Institute Project Title: Streamflow Prediction Using the  NextGen Framework.
PhD Project Title: Streamflow and groundwater level prediction using Long Short-Term Memory Network.

**3.  Project Description:**
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

**4.	Resource Requirements:** 
UA HPC and UA Pantarhei

**5.	Timeline:** 
Summer institute project: June 10th - July 25th
PhD project end date: May 2026
 
**6.	Security and Compliance Requirements:** 
N/A

**7.	Approval:** 
Unknown

**Comment by TrupeshKumarPatel** [comment]
Hello Hossein Gholizadeh (@hgholizadeh7),

Thank you for putting GitHub issues. Now, Pantarhei accesses the next step would be to fill out the [On-Premise Access Request Form](https://forms.office.com/Pages/ResponsePage.aspx?id=jnIAKtDwtECk6M5DPz-8p4IIpHdEnmhNgjOa9FjrwGtUMzdTOUpKVU5UWFNCU0ZQUlowS0cxV0xFRy4u).

**Comment by hgholizadeh7** [comment]
Hello Trupesh,
I just filled out the request form. Please let me know if I need to do anything else.

Thank you very much.

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Hossein Gholizadeh (@hgholizadeh7).

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Anshul Yadav.
