### ISSUE TITLE
New Pantarhei User Ali Sattari

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#196]
BamaID: asattaripirsoltan
Github User name: asattari1991

1. Requester Information:

Requester Name: Ali Sattari

Requester Institution: The University of Alabama

Requester email address: asattaripirsoltan@crimson.ua.edu

PI's Full Name: Jonathan Frame

PI's Affiliated Institute: Lynker

PI's Affiliated Email Address: jframe@lynker.com

2. Project Information:
Summer Institute Project Title: Streamflow Prediction Uncertainty Quantification Using the NextGen Framework.

3. Project Description:
We will use many different software types, depending on the specific training workshop. This will include github, python, and much more.

4. Resource Requirements:
UA HPC and UA Pantarhei

5. Timeline:
Summer institute project: June 10th - July 25th

6. Security and Compliance Requirements:
N/A

7. Approval:
Unknown

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Ali Sattari (@asattari1991).
