### ISSUE TITLE
New Pantarhei User  Surabhi Upadhyay

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#198]
github username: surabhiupadhyay
email: surabhi_upadhyay@mines.edu
BAMA ID: supadhyay1

    Requester Information:

Requester Name: Surabhi Upadhyay

Requester Institution: Colorado School of Mines

Requester email address: surabhi_upadhyay@mines.edu

PI's Full Name: Jonathan Frame

PI's Affiliated Institute: Lynker

PI's Affiliated Email Address: [jframe@lynker.com](mailto:jframe@lynker.com)

    Project Information:
    Summer Institute Project Title: Prediction of Atmospheric Rivers using GOES Satellite data

    Project Description:
    We will use many different software types. This will include github, python, and much more.

    Resource Requirements:
    UA HPC and UA Pantarhei

    Timeline:
    Summer institute project: June 10th - July 25th

    Security and Compliance Requirements:
    N/A

    Approval:
    Unknown

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Surabhi Upadhyay (@surabhiupadhyay).
