### ISSUE TITLE
New Pantarhei User for Meklit Berihun Melesse

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#199]
Requester Information: 

Requester Name: Meklit Berihun Melesse

Requester Institution: Washington State University

Requester email address: m.melesse@wsu.edu

Requester github username: meklit-y

PI's Full Name: Jonathan Frame

PI's Affiliated Institute: Lynker

PI's Affiliated Email Address: [jframe@lynker.com](mailto:jframe@lynker.com)

Project Information:
Summer Institute Project Title: Prediction of Atmospheric Rivers using GOES Satellite data

Project Description:
We will use many different software types. This will include github, python, and much more.

Resource Requirements:
UA HPC and UA Pantarhei

Timeline:
Summer institute project: June 10th - July 25th

Security and Compliance Requirements:
N/A

Approval:
Unknown

**Comment by TrupeshKumarPatel** [comment]
The Pantarhei account is created for Meklit Berihun Melesse (@meklit-y).
