### ISSUE TITLE
UU Access Pantarhei- Snow Water Equivalent ML - Ryan

### ISSUE THREAD

**Issue by whitelightning450** [CIROH-UA/NGIAB-CloudInfra#208]
I would like to request Pantarhei  and AWS access for my Advancing CONUS snow modeling project for my move from the University of Alabama to the University of Utah.

Requester Information:

Requester Name: Ryan Johnson

Requester Institution: University of Utah

Requester email address: ryan.c.johnson@utah.edu

PI's Full Name: Ryan Johnson

PI's Affiliated Institute: University of Utah

PI's Affiliated Email Address: ryan.c.johnson@utah.edu

Project Information: Advancing CONUS-scale Operational Snow Modeling Capabilities

Project Description:
We will use many different software types. This will include github, python, and much more to process data and train ML models

Resource Requirements:
UA HPC, UA Pantarhei
, AWS

Timeline:
now- June 2026

Security and Compliance Requirements:
N/A

Approval:
Unknown

**Comment by arpita0911patel** [comment]
Access is provided by Trupesh. Thank you! Let us know if anything.
