### ISSUE TITLE
OWP HAND-FIM Data Bucket 

### ISSUE THREAD

**Issue by sagycohen** [CIROH-UA/NGIAB-CloudInfra#209]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Sagy Cohen
- PI's Affiliated Institute: University of Alabama
- PI's Affiliated Email Address: Sagy.cohen@ua.edu

**2.	Project Information:** 
As part of a CIROH project, we wish to develop a 'FIM as a Service' and 'FIM in a Box' CIROH community services. 

**3.  Project Description:**
This request is to host the OWP S3 Bucket which contains the pre-calculated HAND rasters and other input needed to run the OWP HAND-FIM.

**4.	Resource Requirements:** 
At this stage, we need to copy the OWP S3 Bucket which is about 1.5TB.

**Options:**
1. Cloud Provider: AWS/Azure/GCP
AWS S3

2. Required Services in the Cloud:
Data storage for applications

   List of AWS Services
   ====================
- S3 – public; Same name and structure and the OWP bucket. 
  
**5.	Timeline:** 
As soon as you can.

**6.	Security and Compliance Requirements:** 
No

**7.	Estimation:** 
Not sure
 
**8.	Approval:** 
No special requirement to my knowledge.

**Comment by benlee0423** [comment]
@sagycohen 
Could you please let me know your preferred name for the S3 bucket?

**Comment by sagycohen** [comment]
Ben,
I’m adding Anupal Baruah to the discussion.
@Anupal ***@***.***>, what is the name of the OWP S3 bucket? Does it make sense to match the name for the CIROH bucket?
Sagy

From: Benjamin Lee ***@***.***>
Date: Friday, July 19, 2024 at 18:40
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Sagy Cohen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] OWP HAND-FIM Data Bucket (Issue #209)

@sagycohen<https://github.com/sagycohen>
Could you please let me know your preferred name for the S3 bucket?

**Comment by sagycohen** [comment]
Hi All

This is the script that I used to list the contents of the HAND FIM. I think we can use different bucket names or we can stick to the same.

!aws s3 ls s3://noaa-nws-owp-fim/hand_fim/ --request-payer



Anupal Baruah
Post Doctoral Fellow
Surface Dynamics Modeling Lab
The University of Alabama
Email: ***@***.***
Phone-+1-659-261-6505/+91-8721886129

________________________________

**Comment by sagycohen** [comment]
Let’s keep the name (‘hand_fim’) – it may simplify script adaptation.

From: Anupal Baruah ***@***.***>
Date: Monday, July 22, 2024 at 09:12
To: Sagy Cohen ***@***.***>, CIROH-UA/NGIAB-CloudInfra ***@***.***>, CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] OWP HAND-FIM Data Bucket (Issue #209)
Hi All

This is the script that I used to list the contents of the HAND FIM. I think we can use different bucket names or we can stick to the same.

!aws s3 ls s3://noaa-nws-owp-fim/hand_fim/ --request-payer




Anupal Baruah
Post Doctoral Fellow
Surface Dynamics Modeling Lab
The University of Alabama
Email: ***@***.***
Phone-+1-659-261-6505/+91-8721886129

________________________________

**Comment by benlee0423** [comment]
@sagycohen 
We can only give public read access if this bucket is open to public.
For writing to this bucket, we have a user assigned and give permission to that user.
Anupal, do you have aws account with us already?

**Comment by sagycohen** [comment]
We need people to be able to download the data. Only admin should be able to upload.

On Jul 22, 2024, at 12:30, Benjamin Lee ***@***.***> wrote:

﻿

@sagycohen<https://github.com/sagycohen>
We can only give public read access if this bucket is open to public.
For writing to this bucket, we have a user assigned and give permission to that user.
Anupal, do you have aws account with us already?

**Comment by benlee0423** [comment]
Bucket is created. Bucket name is globally unique, and I couldn't give the same with original bucket.
Name: noaa-nws-owp-fim-hand-fim

**Comment by sagycohen** [comment]
Can you rename it to ‘owp-hand-fim’?


From: Benjamin Lee ***@***.***>
Date: Monday, July 22, 2024 at 13:46
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Sagy Cohen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] OWP HAND-FIM Data Bucket (Issue #209)

Bucket is created. Bucket name is globally unique, and I couldn't give the same with original bucket.
Name of the bucket: noaa-nws-owp-fim-hand-fim

**Comment by benlee0423** [comment]
`owp-hand-fim` bucket created.

**Comment by arpita0911patel** [comment]
Let's keep it ciroh-owp-hand-fim if that's okay.

**Comment by sagycohen** [comment]
Thanks

From: Benjamin Lee ***@***.***>
Date: Monday, July 22, 2024 at 14:03
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Sagy Cohen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] OWP HAND-FIM Data Bucket (Issue #209)

owp-hand-fim bucket created.

**Comment by sagycohen** [comment]
Yes

From: Arpita Patel ***@***.***>
Date: Monday, July 22, 2024 at 14:10
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Sagy Cohen ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] OWP HAND-FIM Data Bucket (Issue #209)

Let's keep it ciroh-owp-hand-fim if that's okay.

**Comment by benlee0423** [comment]
`ciroh-owp-hand-fim` created

**Comment by arpita0911patel** [comment]
Thank you @benlee0423 . Closing this ticket.
