### ISSUE TITLE
CIROH AWS request

### ISSUE THREAD

**Issue by supathdhitalGEO** [CIROH-UA/NGIAB-CloudInfra#211]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Prof., Dr. Sagy Cohen
- PI's Affiliated Institute: University of Alabama
- PI's Affiliated Email Address: sagy.cohen@ua.edu

**2.	Project Information:** 
I am modeling a flood inundation map using neural network, so The dataset is huge, and sharing dataset with other in a short span of time is not feasible so I am expecting with AWS I can host my dataset there for use. 

**3.  Project Description:**
Modeling a Neural Network. 

**4.	Resource Requirements:** 
Cloud - AWS S3 

**Options:**
1. Cloud Provider: AWS/Azure/GCP

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5.	Timeline:** 
Until 2026 Jan.
 

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by benlee0423** [comment]
@supathdhitalGEO 
Thank you for submitting the request.
I am going to create a s3 bucket with public read access with the following name.
`ciroh-neural-network-map`
If you have any preferred name, please suggest here. If that name is available to use, I will create the bucket with that name.

Also, let me know who will be writing data to this bucket, and have access to aws.

Here is cost estimation of long term storage for your reference.
For S3 Standard 
First 50 TB / Month, $0.023 per GB
Assuming 1TB data storage, monthly cost will be $23.

**Comment by supathdhitalGEO** [comment]
For now 1TB will be sufficient for me, and make **`SDML-surrogate-modeling`** name. 
Whenever I want to make it public I can, right? So, make it private.

**Comment by benlee0423** [comment]
@supathdhitalGEO 
`sdml-surrogate-modeling` bucket created as a private.
Do you have aws account with us? I don't see one.
If you like to get one, and have to access to the bucket, let me know.

**Comment by supathdhitalGEO** [comment]
Yeah sure, please create it and if you have any resources like how to upload data and access it kinda, please share with me.

**Comment by benlee0423** [comment]
@supathdhitalGEO 
S3 bucket: sdmlab
Gave you access key.
Do not share this others and save as a plain text anywhere.
Let me know if you need anything.

**Comment by benlee0423** [comment]
Requested change aws account email to sdml lab email, and waiting on that.
