### ISSUE TITLE
HEFS Project AWS Resource Request

### ISSUE THREAD

**Issue by mgdenno** [CIROH-UA/NGIAB-CloudInfra#213]
**1.	Requester Information:**
Matthew Denno
RTI International
mdenno@rti.org

John Park @gpark69
RTI International
gpark@rti.org

**2.	Link to Existing Infrastructure Ticket:** 
[Provide a ticket created for this project for which extension is being requested.](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/33) 

**3. Justification for increased budget:**
RTI is requesting and increased AWS budget so our AWS sub-account can be utilized for the “Developing and refining ensemble streamflow forecasting through NextGen and the RFC Hydrologic Ensemble Forecast Service” project. The effort, headed by Andy Wood with Gi-Hyeon Park as the Principal Investigator, will use the TEEHR-HUB setup currently being utilized for the CIROH evaluation system at RTI (among others) to provide virtual desktops that allow researchers to experiment with model alternatives benchmarked against the existing HEFS. They will create and deploy a customized FEWS container with options from the HEFS testbed configurations, offering researcher-oriented access via a JupyterHub desktop interface, streamlining the process by removing the need for local FEWS installation and data transfers of ensemble forecasts. This availability of historical and forecast data alongside the default HEFS model within a virtual environment preloaded with FEWS Standalone aims to enhance the evaluation of competing ensemble models.  As part of this effort we will stage up to 10 TB of CONUS-wide HEFS model configurations, forcings and results in an S3 bucket and allow researchers easy access.

**3.	Resource Requirements:** 
This request will run in the existing resources in use for TEEHR-HUB.  We anticipate a monthly S3 storage cost of up to $230/mo. for up to 10TB of HEFS model configurations, forcings and results, with a one-time ingress cost of $306 for 3.4TB.   Additional monthly costs for EC2 and EBS usage are estimated to be about $66/mo.

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2 as nodes for EKS
- S3 – we will use our current bucket.
- EBS (Amazon Elastic Block Store)
- EKS (Kubernetes Cluster)
 
**4.	Timeline:** 
This request is needed immediately and would extend until the the project is over.  The current project extends through May 2025 and there may be extensions requested to extend the end date.
 
**5.	Security and Compliance Requirements:** 
None
 
**6.	Cost Estimation:** 
We anticipate a one time cost of $306 for ingress and up to ~$300/mo. for S3 and EC2/EKS expenses described above.
 
**7.	Approval:** 
Once Form is submitted, we will email the CIROH management to get the approval.

**8. Project to charge to: (For CIROH IT Admin to fill out based on approval process) ** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by mgdenno** [comment]
@arpita0911patel @jameshalgren Not sure if you get notified when these are posted.  Just making sure it is on your radar.

**Comment by arpita0911patel** [comment]
Thank you Matt, noted. Please use RTI Subaccount for the same.
