### ISSUE TITLE
CIROH Google Cloud Functions for NWM WRF-Hydro Domain Subsetter

### ISSUE THREAD

**Issue by fbaig** [CIROH-UA/NGIAB-CloudInfra#214]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Furqan Baig
- PI's Affiliated Institute: University of Illinois Urbana-Champaign
- PI's Affiliated Email Address: fbaig@illinois.edu

**2.	Project Information:** 
The project aims to create a service to subset [domain data version 3](https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/nwm.v3.0.11/parm/domain/) for National Water Model WRF-Hydro model workflow. The data is already available and accessible on CIROH Google Cloud storage at `gs://hydroshare-common-data`. 

**3.  Project Description:**
We plan to execute and possibly automate the [R based domain subsetting code](https://github.com/CUAHSI/notebooks/blob/main/domain-subsetter/rwfrhydro/subset_wrfhydro_domain.ipynb). Since the data is already available on Google Cloud storage, it is best to run the job on GCP resources instead of downloading the data on compute environment.

**4.	Resource Requirements:** 
At this stage, we plan to investigate the feasibility of using GCP Cloud Functions for the above mentioned functionality. We will use [docker](https://github.com/I-GUIDE/wrfhydro-domain-subsetter-v3.0/blob/main/docker/Dockerfile) to manage dependencies.

**Options:**
1. Cloud Provider: AWS/Azure/GCP
    - GCP

2. Required Services in the Cloud:
    - Google Cloud Functions 

   List of GCP Services
   ====================
- Google Cloud Functions 

**5.	Timeline:** 
By next week i.e. 08/26/2024

**6.	Security and Compliance Requirements:** 
N/A 

**7.	Estimation:** 
Not sure yet 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by ciroh-it-admin** [comment]
@jameshalgren

**Comment by arpita0911patel** [comment]
@fbaig is there a way you could provide us the estimates for this runs on Google Cloud?
