### ISSUE TITLE
MMM Project AWS Resource Request - RTI

### ISSUE THREAD

**Issue by kvanwerkhoven** [CIROH-UA/NGIAB-CloudInfra#215]
**1.	Requester Information:**
Katie van Werkhoven
RTI International
[kvanwerkhoven@rti.org](mailto:kvanwerkhoven@rti.org)

Matthew Denno
RTI International
[mdenno@rti.org](mailto:mdenno@rti.org)

**2.	Link to Existing Infrastructure Ticket:** 
Provide a ticket for this project for which extension is being requested. [link](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/33)

**3. Justification for increased budget:**
RTI is requesting and increased AWS budget so our AWS sub-account can be utilized for the CIROH project “Pathways to using multi-model mosaics for operational hydrologic prediction". The lead PI for the project is Martyn Clark and Katie van Werkhoven is the RTI co-PI.  The RTI project team will use the TEEHR-HUB setup currently being utilized for the CIROH evaluation system at RTI (among others) to execute research experiments utilizing TEEHR and large-domain model output from modeling experiments performed at U. Calgary, PSU, and RTI.  The analyses will involve transfer and processing of large model datasets (~5GB) from UCalg and PSU, generation of large model output datasets using the PyMARRMoT modeling framework (up to ~50 GB), and multiple evaluation analyses using TEEHR.  We anticipate 2 RTI researchers will be executing experiments for the MMM project in TEEHR-HUB, each working approximately 15/hours per week on this project.  Approximately 5GB of data from UCalg and PSU will be involved and RTI may generate up to 50 GB of additional model output, which will be transferred to S3 for storage.

**3.	Resource Requirements:** 
This request will run in the existing resources in use for TEEHR-HUB. Additional monthly costs for EC2 and EBS usage are estimated to be about $151.20/mo (150 hours per month of r5.4xlarge EC2 @ 1.008/hour = $151.20).  There would also be some ingress/egress expenses and bucket expenses that are not included but are expected to be insignificant.

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2 as nodes for EKS
- S3 – we will use our current bucket.

**4.	Timeline:** 
This request is needed immediately and would extend until the project ends. The current project extends through May 2025 and there may be extensions requested to extend the end date.
 
**5.	Security and Compliance Requirements:** 
None

**6.	Cost Estimation:** 
We anticipate  ~$160/mo. for EC2/EKS expenses described above and including approximately $10/mo for ingress expenses and S3 storage expenses.
 
**7.	Approval:** 
Once Form is submitted, we will email the CIROH management to get the approval.

**8. Project to charge to: (For CIROH IT Admin to fill out based on approval process) ** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Please use the RTI subaccount for the same and let us know if anything is needed from our end on this. Thank you.

**Comment by Sheargrub** [comment]
Per Slack: end date has been extended to May 31, 2026.

**Comment by arpita0911patel** [comment]
@samlamont - thank you for your message. I understand this is one time cost for now?

**Comment by samlamont** [comment]
@arpita0911patel That's correct, this is a one-time cost for this specific processing job

**Comment by arpita0911patel** [comment]
Closing this ticket as the budget is granted.

**Comment by arpita0911patel** [comment]
Closing this request as access is already available. Let us know if anything.
