### ISSUE TITLE
R2O Coordination Project AWS Resource Request - RTI

### ISSUE THREAD

**Issue by kvanwerkhoven** [CIROH-UA/NGIAB-CloudInfra#216]
**1.       Requester Information:**
Katie van Werkhoven
RTI International
[kvanwerkhoven@rti.org](mailto:kvanwerkhoven@rti.org)

Matthew Denno
RTI International
[mdenno@rti.org](mailto:mdenno@rti.org)

**2.       Link to Existing Infrastructure Ticket:** 
Provide a ticket for this project for which extension is being requested. [link](https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/33)

**3. Justification for increased budget:**
RTI is requesting an increased AWS budget so our AWS sub-account can be utilized for the CIROH project “Research to Operations Coordination".  Under this project, Katie van Werkhoven is working directly with the National Water Center Interdisciplinary Science and Engineering Division (ISED) on a range of activities including helping ISED develop and transition evaluation-related research and tools into use in operational, pseudo-operational (i.e., operational support), or standard practice (i.e., NWC project guidance or support).  A core part of this work is developing and testing tools and procedures for post flood event forecast evaluation and executing evaluations of the NWM baseline datasets (e.g., Retrospective 3.0) using TEEHR.  The RTI Team (primarily Katie vW) and ISED partners (primarily Jason Regina), will use the TEEHR-HUB setup currently being utilized for the CIROH evaluation system at RTI (among others) to execute post event and retrospective evaluations.  The analysis will involve ingress of subsets of the operational NWM forecasts (for post event, retrospective data are already in an S3 bucket) and EC2/EKS usage to execute the analyses.  The exact quantity of data and usage time will depend on need and will vary from month to month based on the occurrence of flood events and requests for evaluation from NWC or other NWS operational centers.  

**3.       Resource Requirements:** 
This request will run in the existing resources in use for TEEHR-HUB. Additional monthly costs for EC2 and EBS usage are estimated to be about $201.60/mo (200 hours per month of r5.4xlarge EC2 @ 1.008/hour = $201.60).  Ingress costs for the operational NWM data are estimated to be $300/mo.  Storage costs will be insignificant (1GB of data per flood event, ~$0.10)

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud:

   List of AWS Services
   ====================
- EC2 as nodes for EKS
- S3 – we will use our current bucket.

**4.       Timeline:** 
This request is needed immediately and would extend until the project ends or the ISED evaluation activities are transferred to another platform. The current project extends through July 2025 and there may be extensions and/or continuations.

**5.       Security and Compliance Requirements:** 
None

**6.       Cost Estimation:** 
We anticipate  ~$500/mo. for EC2/EKS and ingress expenses described above.  Storage costs are expected to be insignificant.

**7.       Approval:** 
Once Form is submitted, we will email the CIROH management to get the approval.

**8. Project to charge to: (For CIROH IT Admin to fill out based on approval process) ** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Please use the RTI subaccount for the same and let us know if anything is needed from our end on this. Thank you.

**Comment by Sheargrub** [comment]
Per Slack: end date has been extended to March 2027.
