### ISSUE TITLE
Change default to match prompt

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB-CloudInfra#217]
https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/3208bda278c91ef08c19d07b9623657fd86cfb59/viewOnTethys.sh#L505C106-L505C123

The prompt shows `y/N` which would indicate "No" as the default answer. We need to correct the text to `Y/n` to properly reflect the current default or (my preference) change the default to No for now. 

@romer8

**Comment by romer8** [comment]
I have added a pull request with the changes [219](https://github.com/CIROH-UA/NGIAB-CloudInfra/pull/219)

**Comment by arpita0911patel** [comment]
This PR is merged so closing this issue.
