### ISSUE TITLE
Cloud Resources for Delft-FEWS System - Yukon River Basin - Uni of Calgary

### ISSUE THREAD

**Issue by DaveCasson** [CIROH-UA/NGIAB-CloudInfra#218]
Request for Cloud Resources for Delft-FEWS system

1. Requester Information

Name: David Casson
Title: PhD Candidate, University of Calgary
Email: [dave.casson@ucalgary.ca](mailto:dave.casson@ucalgary.ca)

2. Project Information

Project Title: OpenFEWS: A operational Delft-FEWS / CHPS forecasting testbed for the Yukon River Basin

Brief Description:

Transitioning CIROH and NextGen research developments to River Forecast Centers (RFCs) can be facilitated by developing workflows in Delft-FEWS / CHPS software. This allows innovations in modelling and forecasting to be put directly in this framework that RFCs use every day. 

An initial system has been developed in collaboration with the Alaska-Pacific River Forecast Center (APRFC) as part of the project
_Improving the process representations and predictive performance of the next generation Water Resources Modeling framework in cold regions: The Yukon River Basin_.

This resource request is to install an operational version of this system, hosted on CIROH cloud environment.

Benefit

This allocation will provide a direct mechanism to bring hydrological forecasting research to operations. It has been discussed and meet with approval by the APRFC. This provides a path for NextGen use by the RFCs, through future NextGen integration in FEWS / CHPS

3. Project Description

Software and Tools:

An overview of Delft-FEWS components is summarized here:
https://publicwiki.deltares.nl/display/FEWSDOC/Delft-FEWS+Hardware+and+software+requirements+-+2023.02

Cloud installation is described here:
https://publicwiki.deltares.nl/display/FEWSDOC/Delft-FEWS+and+the+cloud

The installation will be in Linux environments. 
The [SUMMA Modelling Framework Software](https://summa.readthedocs.io/) will be installed, as well as Python scripting.

Workflow:
Workflows will involve the access of external data sources (hydrological data, NWP data sources, NextGen forcing), processing and application to hydrological modelling for forecasting. The workflows are developed and run via Delft-FEWS.

4. Resource Requirements

The base requirements of Delft-FEWS are described in the link here: https://publicwiki.deltares.nl/display/FEWSDOC/Delft-FEWS+Hardware+and+software+requirements+-+2023.02

The data I/O will need to be established as the forecasting system is operationalized. Effort will be made to reduce unnecessary transfer, however it is a necessary component of the operational system.

Preferred Providers: AWS or Azure

Specific technical questions regarding the Delft-FEWS installation can also be handled with a call set-up with Deltares and Delft-FEWS product management.

**Comment by jameshalgren** [comment]
Hi Dave -- with the Azure/AWS request here, are you looking at dynamic machine allocation somehow or will this be primarily a virtual machine implementation? (If #2, would a VM on Jetstream work?-- https://docs.jetstream-cloud.org/general/vmsizes/)
Will you be running Linux or will you need windows OS for any of this work?

**Comment by arpita0911patel** [comment]
Access is granted to Dave Casson on NSF Allocation for JetStream.

**Comment by DaveCasson** [comment]
Can we please add Darri Eythorsson <darri.eythorsson@ucalgary.ca>, @DarriEy to this allocation?
He is a Post-Doc on this CIROH Yukon project.

**Comment by arpita0911patel** [comment]
Sure, Darri please go ahead and create a user on [access-ci.org](http://access-ci.org/). We would be able to add you then.

**Comment by arpita0911patel** [comment]
@DarriEy - you should have access now.

**Comment by arpita0911patel** [comment]
Closing this ticket as access is granted. Please let us know incase of anything. Thank you!
