### ISSUE TITLE
Have access to my previous UA buckets on my new UU AWS S3 account

### ISSUE THREAD

**Issue by whitelightning450** [CIROH-UA/NGIAB-CloudInfra#221]
I want to see the buckets while logged into AWS S3 that I previously managed while at UA, as that is where we stored all of our project data. I think they were national-snow-model and streamflow-evaluator-tool.

**Comment by benlee0423** [comment]
@whitelightning450 
Here is what I will do. Please confirm it.
Two buckets will be moved to new Utah subaccount along with the following users.
Dane liljestrand and Ethan Ritchie
UI access to aws console is enabled on these users.
Karnesh Jain will stay in UA subaccount, but continue have access buckets through cli.

**Comment by benlee0423** [comment]
Ryan's buckets are stayed with UA subaccount along with his new account.
