### ISSUE TITLE
S3 Request for MHPI group BMI codes

### ISSUE THREAD

**Issue by taddyb** [CIROH-UA/NGIAB-CloudInfra#222]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Chaopeng Shen
- PI's Affiliated Institute: Penn State University
- PI's Affiliated Email Address: shen.chaopeng@gmail.com 

Additional points of contact: Tadd Bindas, Leo Lonzarich (Penn State)
- Affiliated Email Address: taddbindas@gmail.com, lgl5139@psu.edu

**2.	Project Information:** 
We are working on making our Differentiable models compatible with nextgen BMI, and working group 2, standards. To ensure users are able to run sample datasets, we are requesting an s3 bucket to handle small example datasets for people to experiment on and learn differentiable modeling. 

**3.  Project Description:**
We plan to develop an open sourced package for training BMI-compliant differentiable models

**4.	Resource Requirements:**

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud:
- S3 – public, named: "MHPI-Spatial"

**5. Working Group Detail**

Working Group 2

**6.	Timeline:** 
We are looking to have a beta version of our product out on Nov 15th, 2024 (4-weeks)

**7.	Security and Compliance Requirements:** 
None
 

**8.	Estimation:** 
We are looking to store ~20GB worth of example datasets with all codes run locally on user compute. Any additional storage would be run by CIROH
 
**9.	Approval:**

**Comment by benlee0423** [comment]
@taddyb 
Bucket is created with name mhpi-spatial because it does not allow uppercase in bucket name.
This bucket is read-only access to the public, but we like to know who will be writing to this bucket.

**Comment by arpita0911patel** [comment]
Permission is provided to everyone in this list. Please let us know if anything. Closing this now.
