### ISSUE TITLE
Pantarhei Resource Request for CIROH FY23 Project

### ISSUE THREAD

**Issue by FariSoltani** [CIROH-UA/NGIAB-CloudInfra#224]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Dr. Bong-Chul Seo
- PI's Affiliated Institute: Missouri University of Science and Technology
- PI's Affiliated Email Address: bongchul.seo@mst.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

We conduct a CIROH FY23 project titled “Comparative Assessment of the NWM Channel Routing Models for Enhanced Streamflow Data Assimilation” to evaluate channel routing models included in T-Route and explore the effect of streamflow data assimilation. One of the project objectives is to run T-Route within the NextGen framework by connecting it with other runoff generation models (e.g., CFE). We will benefit from the CIROH computational resources when running a computing-intensive channel routing model (i.e., diffusive wave routing) and will share our findings and developments with the CIROH community.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.
We evaluate a streamflow assimilation scheme in T-Route and plan to improve the current assimilation scheme with the Muskingum-Cunge method. We also plan to develop and implement a new assimilation scheme for the diffusive wave method with which streamflow assimilation is not currently capable. 

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.
We plan to run T-route for multiple basins (ranging from 200 km2 to 20,000 km2) and multiple (continuous) years.

**Options:**
1. HPC or VM: HPC
  
2. vCPU: We can start from a basic number of CPUs if it is scalable as our demand increases.

3. Memory: 16GB?

4. Disk Space: 1TB? (scalable?)

5. Pantarhei/Wukong/NSF Allocations-JetStream (specify one): Pantarhei

**5. Working Group Detail**
Working Group 1/2/3/4 (select one): 1

**6.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.

 We would like to have the resources as soon as possible, and the project will end in November 2025.

**7.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

None

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

None

**Comment by arpita0911patel** [comment]
@FariSoltani , access is granted. Please test on your end and let us know if anything.
