### ISSUE TITLE
Machine learning and data assimilation for the Nextgen framework - Austin Raney

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB-CloudInfra#225]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Jonathan Frame
- PI's Affiliated Institute: University of Alabama
- PI's Affiliated Email Address: jmframe@ua.edu

**2.	Project Information:** 
Machine learning and data assimilation for the Nextgen framework. 

**3.  Project Description:**
Machine learning and data assimilation for the Nextgen framework. 

**4.	Resource Requirements:** 
VPN access to get on Pantarhei and JetStream

**5. Working Group Detail**

Working Group 1/2/3/4 (select one): 2

**6.	Timeline:** 
October 2024 through August 2025.
 

**7.	Security and Compliance Requirements:** 
N/A

 
**8.	Approval:** 
?

**Comment by TrupeshKumarPatel** [comment]
Hello @jmframe,
I think `Austin Raney` already has a UA campus ID, so I believe he should have VPN access. Please let him know so he can try it once to ensure it works.

**Comment by arpita0911patel** [comment]
Closing this since access is granted.
