### ISSUE TITLE
HPC Computing Resource Request

### ISSUE THREAD

**Issue by feng10** [CIROH-UA/NGIAB-CloudInfra#227]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Matthew Womble
- PI's Affiliated Institute: Alabama Water Institute
- PI's Affiliated Email Address: mwomble@ua.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*
CIROH R2O project.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

Request to get access to the high-performance computing resources.

**Options:**
1. HPC or VM
  
2. vCPU

3. Memory

4. Disk Space

5. Pantarhei/Wukong/NSF Allocations-JetStream (specify one)

**5. Working Group Detail**

Working Group 1/2/3/4 (select one): N/A

**6.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.
 

**7.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Resolved: Xia now has Pantarhei access. Thank you Trupesh.
