### ISSUE TITLE
Storage for website backups

### ISSUE THREAD

**Issue by AdamWarnock-UA** [CIROH-UA/NGIAB-CloudInfra#236]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.
- PI's Full Name: Adam Warnock
- PI's Affiliated Institute: Alabama Water Institute
- PI's Affiliated Email Address: akwarnock@ua.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

This is to store backups of the website that can be reverted to in case of an issue during an upgrade or if something gets lost while updating the site's content.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

This is just storage for backups. Specific details about how it should be set up can be found here: https://duplicator.com/knowledge-base/amazon-s3-step-by-step/

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

Would like 150 gigabytes of storage to allow for multiple full backups.

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud: s3, Page linked above has a link to the JSON for the needed security policy, bucket name: awi-website-backups with a folder for ciroh.ua.edu

   List of AWS Services
   ====================
- EC2
- S3 – public, private, requester pay, bucket name suggestion?
- EBS (Amazon Elastic Block Store)
- EFS
- RDS
- VPC (Virtual Private Cloud)
- DynamoDB
- ECS
- EKS (Kubernetes Cluster)
- Lambda
- Others: please list
  
   List of Azure Services
   ====================
- Virtual Machines
- Azure App Service
- Azure Kubernetes Service (AKS)
- Azure Functions
- Azure Batch
- Azure Blob Storage
- Azure File Storage
- Azure Machine Learning
- Azure Key Vault
- Other: please list

   List of GCP Services
  ====================
- Google Compute Engine
- Google Kubernetes Engine (GKE)
- Google Cloud Storage
- Google VPC
- Google IAM
- Google BigQuery
- Google Cloud Functions
- Dataflow
- Other: please list

**5. Working Group Detail**

Working Group 1/2/3/4 (select one):  Not sure where this would fit in.

**6.	Timeline:** 
Indicate the expected timeline for the project and when the resources will be needed. This information can help the infrastructure team plan and allocate resources accordingly.

If at all possible, I'd like to have this done by December 6th, 2024. Apologies for the short notice.
 

**7.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.

As far as I'm aware there are no security or compliance requirements for this beyond the usual precautions to prevent a data-breach. Access should be limited to AWI communications team and anyone else that Matt Womble or Steve Burian says needs to have access.

**8.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

Estimate can be found here: https://calculator.aws/#/estimate?id=61360298fef3e75ec86e812c0f3aa1412440589c

I'm not 100% on my assumptions. I'd like 150 GB of storage and I don't plan on transferring more than 50 GB/month into it. Ideally, we'd never have to retrieve the data here.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**9.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.
I am not aware of any additional approvals that need to be made. This is for backing up the website. May need to clear it with Matt Womble.

**Comment by benlee0423** [comment]
@AdamWarnock-UA 
Bucket is created.
Let me know if you need access key that was described in [this link](https://duplicator.com/knowledge-base/amazon-s3-step-by-step/).

**Comment by benlee0423** [comment]
@AdamWarnock-UA 
I have provided all details through email.
Please close this ticket if all works and there is no other needs.

**Comment by AdamWarnock-UA** [comment]
Thanks, it's all working so far. I'll close the issue on GitHub.

Adam Warnock
Web Strategist, Alabama Water Institute
The University of Alabama<https://www.ua.edu/>
Box 870206
Tuscaloosa, AL 35487
Mobile 334-300-3908<tel:334-300-3908>
***@***.******@***.***> | http://awi.ua.edu<http://awi.ua.edu/>
[The University of Alabama single line nameplate design without box A]<https://www.ua.edu/>

From: Benjamin Lee ***@***.***>
Sent: Tuesday, November 26, 2024 10:49 AM
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Adam Warnock ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] Storage for website backups (Issue #236)


@AdamWarnock-UA<https://github.com/AdamWarnock-UA>
I have provided all details through email.
Please close this ticket if all works and there is no other needs.

-

**Comment by AdamWarnock-UA** [comment]
Hey Ben, can you set up a folder on that bucket for each of the following?
AWI
WaterNRT
GWSC

Thanks!

From: Adam Warnock ***@***.***>
Date: Tuesday, November 26, 2024 at 10:50 AM
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>, CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] Storage for website backups (Issue #236)
Thanks, it’s all working so far. I’ll close the issue on GitHub.

Adam Warnock
Web Strategist, Alabama Water Institute
The University of Alabama<https://www.ua.edu/>
Box 870206
Tuscaloosa, AL 35487
Mobile 334-300-3908<tel:334-300-3908>
***@***.******@***.***> | http://awi.ua.edu<http://awi.ua.edu/>
[The University of Alabama single line nameplate design without box A]<https://www.ua.edu/>

From: Benjamin Lee ***@***.***>
Sent: Tuesday, November 26, 2024 10:49 AM
To: CIROH-UA/NGIAB-CloudInfra ***@***.***>
Cc: Adam Warnock ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [CIROH-UA/NGIAB-CloudInfra] Storage for website backups (Issue #236)


@AdamWarnock-UA<https://github.com/AdamWarnock-UA>
I have provided all details through email.
Please close this ticket if all works and there is no other needs.
