### ISSUE TITLE
Error when running in parallel mode with AWI_16_2863657_007 input data on Windows

### ISSUE THREAD

**Issue by manjilasingh** [CIROH-UA/NGIAB-CloudInfra#238]
While running ngiab in parallel mode with AWI_16_2863657_007 input data on Windows, it causes a floating-point exception during the partitioning step.

## Current behavior
During the partitioning step, it logs: `Partitioning 241 catchments into 0 partitions` and throws a floating-point exception.
## Expected behavior
It should partition the catchments correctly and run the model in parallel mode without errors.

## Steps to replicate behavior (include URLs)

**Step 1: Create Project Directory**

-  Open WSL with administrator privileges and execute:
```bash
cd /mnt/c/Users/
ls
cd <User Folder>
```

```bash
mkdir -p NextGen/ngen-data
```

```bash
cd NextGen/ngen-data
```
**Step 2: Download Sample Data**

-  Use wget to download the compressed data file:
```bash
wget --no-parent https://ciroh-ua-ngen-data.s3.us-east-2.amazonaws.com/AWI-007/AWI_16_2863657_007.tar.gz
```

**Step 3: Extract and Rename**

-  Extract the downloaded file and optionally rename the folder:
```bash
tar -xf AWI_16_2863657_007.tar.gz
```
```bash
mv AWI_16_2863657_007 my_data
```

**Step 3: Clone the Repository:**
Go to the folder created earlier during step 1 above

```bash
cd NextGen
```
```bash
git clone https://github.com/CIROH-UA/NGIAB-CloudInfra.git
```
```bash
cd NGIAB-CloudInfra
```

**Step 5: Run the Guide :**
```bash
./guide.sh
```
If you encounter a 401 Unauthorized error, re-run the script:
```bash
sudo ./guide.sh
```
**Step 6: Follow the prompts:**
    - **Input Data Path:** Enter the path to your downloaded or generated input data directory. (e.g NextGen/ngen-data/my_data)
    - **Run Mode:** Choose to run ngiab in parallel mode.

## Screenshots
![Screenshot 2024-11-25 160240](https://github.com/user-attachments/assets/e2aac63c-8968-4898-8b4d-6ba535906281)

**Comment by JoshCu** [comment]
This line is probably causing the issue https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c35bc8116171ee937b1b42b899986df38ffd0488/docker/HelloNGEN.sh#L91 data produced with the preprocessor now has the forcings in a netcdf so this will set it to 0. 
The code was originally added to stop 4 catchments being partitioned into more than 4 partitions. It should probably be removed for now to fix the issue then revisited later.

**Comment by arpita0911patel** [comment]
@manjilasingh please retest based on changes in above PR.

**Comment by manjilasingh** [comment]
@arpita0911patel 
I've tested the PR and it's working fine now.
