### ISSUE TITLE
No ARM version for TEEHR Evaluation

### ISSUE THREAD

**Issue by ZacharyWills** [CIROH-UA/NGIAB-CloudInfra#246]
Short description explaining the high-level reason for the new issue.

## Current behavior
when running workflow on ARM, the TEEHR evaluation step doesn't find a matching manifest for linux/arm64/v8

## Steps to replicate behavior (include URLs)

1. run workflow on ARM, opt into TEEHR Eval

**Comment by benlee0423** [comment]
Thank you @ZacharyWills.
We found the issue, and already working on it with Teehr team.

**Comment by benlee0423** [comment]
1. Replace python:3.10-slim-bullseye to python:3.11.11-slim-bookworm, because bullseye does not have gdal > 3.5. bookwarm have gdal > 3.5 at https://packages.debian.org/bookworm/libgdal-dev
2. In arm64, we need multistage build to reduce the final image size. build-essential needs to during build. Otherwise, it gets the following error.
```
Resolved 118 packages in 13.67s                                                                                                                                      
#0 39.50   × Failed to download and build `fiona==1.10.1`                                                                                                                     
#0 39.50   ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status:                                                                                        
#0 39.50       1)
#0 39.50 
#0 39.50       [stderr]
#0 39.50       /tmp/.tmpwctSxc/builds-v0/.tmpl0iBxN/lib/python3.11/site-packages/setuptools/_distutils/extension.py:139:
#0 39.50       UserWarning: Unknown Extension options: 'cython_compile_time_env'
```
3.

**Comment by benlee0423** [comment]
Fixed version of Dockerfile is here.
https://github.com/CIROH-UA/ngiab-teehr/blob/main/Dockerfile

**Comment by benlee0423** [comment]
TODO:
Automate the build using actions.

Note: arm64 runner is not free to use. More details describes [here](https://docs.github.com/en/actions/using-github-hosted-runners/using-larger-runners/running-jobs-on-larger-runners?platform=mac).

**Comment by benlee0423** [comment]
Here is output of teehr in x86 and arm64 ( mac os).
<img width="1002" alt="Screenshot 2024-12-07 at 9 16 20 PM" src="https://github.com/user-attachments/assets/aea7e740-482e-42c7-96e1-6d3d77157580">

**Comment by benlee0423** [comment]
@arpita0911patel 
Can close this. I already tested on both x86 and arm64, and worked both.

**Comment by arpita0911patel** [comment]
thank you Ben. @samlamont closing this ticket. Please let us know if anything.

**Comment by samlamont** [comment]
thank you @benlee0423 and @arpita0911patel for your help on this!
