### ISSUE TITLE
NGIAB End-to-End Setup - Visualizing Outputs Using the Tethys Platform: Prompt Says "Y" for Yes, But Only "y" Works

### ISSUE THREAD

**Issue by imanmaghami** [CIROH-UA/NGIAB-CloudInfra#247]
In the [NGIAB End-to-End Setup Guide](https://docs.ciroh.org/docs/products/Community%20Hydrologic%20Modeling%20Framework/nextgeninaboxDocker/workflow/), the prompt for visualizing outputs using the Tethys Platform says to enter "Y" for yes, but entering "Y" results in an invalid choice error. Only lowercase "y" is accepted. This is inconsistent with the message and should be fixed.

See attached screenshot for reference.
![image_2024-12-05_13-11-05](https://github.com/user-attachments/assets/16d7bbcf-c056-49bd-b1ca-98eb21798fef)

**Comment by arpita0911patel** [comment]
yes @benlee0423 that should be fine

**Comment by JoshCu** [comment]
originally I think the `Y/n` got added where the default was yes, for clarity the (default: Y) was added. The standard is usually that the selection is case insensitive and the capital letter is just to show which option is the default, but I didn't want to assume every user would know that.

![image](https://github.com/user-attachments/assets/310967f4-9770-4a28-a36a-5a583822a96d)

**Comment by benlee0423** [comment]
@imanmaghami 
I do the same and it worked for me. And the script that check accept any of "yYnN" as valid input.
What version of ngiab are you using in guide.sh?

```
Darwin UA-QG4YJKY 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64
Visualize outputs using the Tethys Platform (https://www.tethysplatform.org/)? (Y/n, default: n):
Y
Setting up Tethys Portal image...
Select an option (type a number): 

1) Run Tethys using existing local docker image
2) Run Tethys after updating to latest docker image
3) Exit
```

**Comment by benlee0423** [comment]
`if [[ "$visualization_choice" =~ ^[YyNn]$ ]]; then`

This code in script is used to validate the input variable $visualization_choice to ensure that it only contains the values "Y", "y", "N", or "n".

**Comment by imanmaghami** [comment]
Hi @benlee0423,

Thank you for your patience as I’m still getting up to speed here! Just to clarify, when you mention NGIAB, are you referring to the NGIAB-CloudInfra repository? If so, I checked the version currently in use, and it appears to be v1.3.0 based on the following command output:

```
(.venv) root@Iman:/NGIAB-CloudInfra# git describe --tags
v1.3.0
```

**Comment by benlee0423** [comment]
@imanmaghami 
This is the same piece of code. Can you save it in .sh file and run the file from your command line, and share your output?

```
visualization_choice="y"
if [[ "$visualization_choice" =~ ^[YyNn]$ ]]; then
    echo "Valid input: $visualization_choice"
else
    echo "Invalid input: $visualization_choice"
fi
```

Output should `Valid input: y`

**Comment by imanmaghami** [comment]
@benlee0423 Sorry for delay. I followed your instructions. And got this: 
![image](https://github.com/user-attachments/assets/cf50de48-846c-4516-ab53-5e2622f69b8e)
Does everything look correct to you?

**Comment by dan1831** [comment]
Tested with y and Y, passed for both.
