### ISSUE TITLE
PET library file missing

### ISSUE THREAD

**Issue by JordanLaserGit** [CIROH-UA/NGIAB-CloudInfra#248]
It appears the PET library file is missing from `/dmod/shared_libs/` in the new 1.3.0 NGIAB container. In previous builds, this file had been located at `/dmod/shared_libs/libpetbmi.so.1.0.0`.

**Comment by benlee0423** [comment]
In 1.3.0
```
# find / -name '*pet*'
/ngen/.venv/lib/python3.9/site-packages/pyarrow/include/arrow/vendored/portable-snippets
# ls /dmod/shared_libs/
libcfebmi.so  libcfebmi.so.1.0.0  libiso_c_bmi.so  libslothmodel.so  libslothmodel.so.1.0.0  libsurfacebmi.so  libtopmodelbmi.so  libtopmodelbmi.so.1.0.0
```

In 1.2.1
```
bash-5.1# ls /dmod/shared_libs/
libcfebmi.so	    libiso_c_bmi.so  libpetbmi.so.1.0.0  libslothmodel.so.1.0.0  libtopmodelbmi.so
libcfebmi.so.1.0.0  libpetbmi.so     libslothmodel.so	 libsurfacebmi.so	 libtopmodelbmi.so.1.0.0
```

@JoshCu 
Any idea how it is not there with new Dockerfile we changed?

**Comment by benlee0423** [comment]
Guess this line could be missing that file?
https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c91299b13dfaf0d867046786a5f262845b6d5656/docker/Dockerfile#L126

**Comment by JoshCu** [comment]
> Guess this line could be missing that file?
> 
> https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/c91299b13dfaf0d867046786a5f262845b6d5656/docker/Dockerfile#L126

That looks like the problem, I missed out the pet subdirectory when I translated it from this https://github.com/CIROH-UA/NGIAB-CloudInfra/blob/170646ed2740a03ec2c78a4f7032db24e41b4e08/docker/Dockerfile#L19C14-L22C14

if rocky supports the /**/ directory wildcard then it might be as simple as changing

```dockerfile
cp -a ./extern/*/cmake_build/*.so* /dmod/shared_libs/. || true && \ 
# to this
cp -a ./extern/**/cmake_build/*.so* /dmod/shared_libs/. || true && \ 
```
I'm testing it out now to see where it loses the .so

**Comment by JoshCu** [comment]
![image](https://github.com/user-attachments/assets/25efa12e-00fa-42ca-a21c-25dae3f11697)
success!

**Comment by benlee0423** [comment]
Thank you @JoshCu  for the quick fix.
