### ISSUE TITLE
AWS Resource Request - HydroServer - USU

### ISSUE THREAD

**Issue by kjlippold** [CIROH-UA/NGIAB-CloudInfra#35]
**1.	Requester Information:**
This should include the name and contact information of the person making the request.

Name: Ken Lippold
Institution: Utah State University
Position: Software Engineer
Email: kenneth.lippold@usu.edu

**2.	Project Information:** 
Provide a brief description of the project and its goals. This can help the infrastructure team understand the context and purpose of the requested resources. *Please highlight how this project will be benefit from and/or provide benefit to other resources on the shared infrastructure.*

Project title:
CIROH: Modernized Standards and Tools for Sharing and Integrating
Real-time Hydrologic Observations Data

Project summary:
https://ciroh.ua.edu/research-projects/modernized-standards-and-tools-for-sharing-and-integrating-real-time-hydrologic-observations-data/

The purpose of this deployment is to demo and test the current version of HydroServer and receive feedback from the community to identify issues that need to be addressed and discuss ideas for additional features we may want to add.

**3.  Project Description:**
If your project involves developing software or scripts, briefly describe the software you plan to develop.

We are developing several components related to this project which can be found here: https://github.com/hydroserver2

Specifically, the components we want to deploy are found in the hydroserver-webapp-front and hydroserver-webapp-back repositories and are the core of the HydroServer development. Our frontend HydroServer website is built in Vue 3 and will be deployed via Cloudfront/S3, and our backend HydroServer data management and SensorThings APIs are built with Django and will be deployed via Elastic Beanstalk.

**4.	Resource Requirements:** 
Specify the compute, storage, and network resources needed for the project. Be as specific as possible about the number of resources required, and any specific configurations or capabilities needed. This information will help the infrastructure team determine the appropriate resources to allocate.

**Options:**
1. Cloud Provider: AWS

2. Required Services in the Cloud:
- Cloudfront: Used as a CDN for the HydroServer website and as a reverse proxy to route traffic between the website and Django APIs. We use one distribution per deployment.
- Elastic Beanstalk: Used to host the HydroServer Django application, which includes the data management and SensorThings APIs. We use one environment per deployment.
- S3: Used to store website static files and user uploaded photos. We use three buckets per deployment, all of which are private and publicly accessible only through Cloudfront. One bucket is used for the website static files, another is used for user resource storage, such as photos, and the third is used for hosting downloadable desktop applications such as our Streaming Data Loader tool.
- SES: Used primarily for user email verification and password reset. We had our current account removed from sandbox mode to avoid needing to manually whitelist individual email accounts.
- EC2: Mostly used by Elastic Beanstalk, but we also need to configure some additional security settings directly through the EC2 dashboard.

We're using a service called Timescale Cloud to manage our main database deployment since Amazon RDS doesn't support timescale for postgresql. We're planning to continue using our own account for that in the meantime, but we can discuss other options if needed; I don't know if CIROH is able to manage any services outside the ones listed.

Detailed AWS deployment instructions can be found here: https://hydroserver2.github.io/hydroserver/deployment/aws-deployment.html

This documentation is still a work in progress as we find issues and improve our deployment process.

**5.	Timeline:** 
We currently have a test instance of HydroServer deployed on a separate AWS account and have documented the deployment steps. We can deploy an instance under the CIROH account as soon as the resources are ready, but we're flexible with the timeframe since we have an existing deployment we can use in the meantime.

**6.	Security and Compliance Requirements:** 
We don't currently have any special security or compliance requirements for this testing deployment. Initially, we anticipate this deployment will be primarily used for demos and testing. I can provide additional details about our existing IAM security policies and roles if needed, but I assume they'll need to be narrower under CIROH's account.
 

**7.	Estimation:** 
Based on our current AWS bills, we expect the monthly cost to be under $50, depending on how much traffic the demo site gets or if we decide to create additional deployments.

**8.	Approval:** 
Jeff Horsburgh: jeff.horsburgh@usu.edu

**Comment by arpita0911patel** [comment]
We appreciate your request submission. Kindly provide a list of email addresses for the users requiring access to this USU Subaccount within the CIROH AWS Account.

**Comment by arpita0911patel** [comment]
@kjlippold , please let us know if you face any issues using the services under USUAWSAdmin subaccount.

**Comment by arpita0911patel** [comment]
Closing this request as access is provided to USU subaccount for this project.
