### ISSUE TITLE
Machine Learning training resource - Pantarhei

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB-CloudInfra#38]
@jmframe
Will you fill out this information with respect to the restoration of the Pantarhei cluster? This form is usually used for CIROH members to document computing resource needs -- we have already started to move forward with Pantarhei but it would help to build this back in.

**Comment by jameshalgren** [comment]
@TrupeshKumarPatel FYI

**Comment by arpita0911patel** [comment]
Pantharhei cluster has been restored by XISS and Trupesh is able to give user access.
