### ISSUE TITLE
Request to use Sagemaker for Project 8: Enhancing Water Supply Forecasting for Systems Management - UA

### ISSUE THREAD

**Issue by savalann** [CIROH-UA/NGIAB-CloudInfra#41]
**1.	Requester Information:**

Savalan Naser Neisary (snaserneisary@crimson.ua.edu)
Ryan Johnson (rjohnson18@ua.edu)
Md Shahabul Alam (malam24@ua.edu)

**2.	Project Information:** 

The goal of this project is to enhance NWM predictions downstream of the Great Salt Lake (GSL) watershed. We need to run machine learning models that require GPUs and cloud computing (Sagemaker and S3 buckets) with preinstalled Pytorch and Tensorflow packages. 

**3.  Project Description:**

The scripts and software we plan to develop gets different variables and NWM predictions and post-process them using ML models. 

**4.	Resource Requirements:** 

1. Development interface for Python code, which also has access to the internet, such as Sagemaker or Jupyter Notebook. 
2. GPUs (I don't know how many).
3. S3 bucket. 
4. Preinstalled Pytorch libraries. 

6. Required Services in the Cloud:

   List of AWS Services
   ====================
- S3 – public, private, requester pay, bucket name suggestion?

**5.	Timeline:** 

We need it ASAP, and we'll use it for the coming next 2 years.

**6.	Security and Compliance Requirements:** 
If there are any specific security or compliance requirements for the project, these should be clearly stated in the request. This will help ensure that the necessary security measures are in place for the project.
 

**7.	Estimation:** 
Include any cost estimation or requirements for the project. This will help the infrastructure team select the most cost-effective solutions for the project.

AWS Cost Calculator: https://calculator.aws/#/

Google Cloud Pricing Calculator: https://cloud.google.com/products/calculator
 

 
**8.	Approval:** 
Indicate the necessary approval processes or sign-offs required for the request.

**Comment by arpita0911patel** [comment]
Hi Savalan,

Based on our conversation here is the cost estimate for your request for 1 GPU instance and 1 TB storage.

Arpita

**Comment by arpita0911patel** [comment]
SageMaker access is granted to Ryan and Savalan for the above request for P8 project. To create a role and policy to run a Jupyter notebook I can help setup if needed.
