### ISSUE TITLE
CFE output files (cat-*.csv) results are all zero

### ISSUE THREAD

**Issue by shahab122** [CIROH-UA/NGIAB-CloudInfra#44]
Hi everyone, I have run CFE using NGIAB for the Sipsey River basin (VPU # 03W) in Alabama. As I was checking the model outputs (e.g., "cat-117770.csv"), I found all values in the"cat-117770.csv" file to be zero. This is the case for all catchment csv files. I used "latest-86" image as I was running CFE within NGIAB on Black Warrior. I am not sure what went wrong as I followed the steps mentioned here: https://github.com/CIROH-UA/NGIAB-CloudInfra.   

Screenshot of results with troute on:
![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/28275758/912ee598-98d7-4241-893c-a03f90c85ae3)

Screenshot of results with troute off:
![image](https://github.com/CIROH-UA/NGIAB-CloudInfra/assets/28275758/99ae449a-d944-4534-801f-c13636246dd3)

**Comment by arpita0911patel** [comment]
@jameshalgren

**Comment by arpita0911patel** [comment]
This is the sloth configuration here that is producing csv output files: 

`{
                            "name": "bmi_c++",
                            "params": {
                                "name": "bmi_c++",
                                "model_type_name": "SLOTH",
                                "main_output_variable": "z",
                                "init_config": "/dev/null",
                                "allow_exceed_end_time": true,
                                "fixed_time_step": false,
                                "uses_forcing_file": false,
                                "model_params": {
                                    "sloth_ice_fraction_schaake(1,double,m,node)": "0.0",
                                    "sloth_ice_fraction_xinan(1,double,1,node)": "0.0",
                                    "sloth_smp(1,double,1,node)": "0.0",
                                    "EVAPOTRANS": "0.0"
                                },
                                "library_file": "/dmod/shared_libs/libslothmodel.so",
                                "registration_function": "none"
                            }
                        }
`

**Comment by hellkite500** [comment]
Two options here, one, change the order of the multi bmi module definitions so that sloth comes first in the list and CFE is last.  By default, ngen will only output the output variables of the LAST modules defined in a multi-bmi model definition.  The other option is to use the optional configuration key
```json
"output_vars" : [ "Q_OUT", "OTHER_KNOWN_OUTPUT_VAR"]
```
With this list, you can explicitly define any output variable available in any of the modules, and the order they will appear in the output CSV file.

**Comment by arpita0911patel** [comment]
First option works for me. It produces the output cat-*.csv files with the outputs. Thank you Nels, I will add the updated one to the AWI_002

**Comment by arpita0911patel** [comment]
Updated AWI_03W_113060_002.tar.gz in S3 bucket with the new config file.

**Comment by arpita0911patel** [comment]
@shahab122, could you please review the most recent updates and confirm that everything appears satisfactory on your end? Please inform us of any issues or concerns. Thank you!

**Comment by arpita0911patel** [comment]
Thank you Shahab closing this ticket as it generated non zero output cat-*.csv files now.
For the flowveldepth file, created seperate ticket https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/61
