### ISSUE TITLE
Create a PR validation pipeline 

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB-CloudInfra#49]
pipeline to validate PRs

**Comment by arpita0911patel** [comment]
Added changes on top of this branch :  https://github.com/CIROH-UA/NGIAB-CloudInfra/tree/build-refactor 

Let's test and merge this branch once seg fault issue is resolved.

**Comment by arpita0911patel** [comment]
https://github.com/CIROH-UA/NGIAB-CloudInfra/issues/86

**Comment by benlee0423** [comment]
@arpita0911patel 
This can be closed because PR from forked branch works now.
