### ISSUE TITLE
Restarting CFE simulation within NextGen 

### ISSUE THREAD

**Issue by KJafarzadegan** [CIROH-UA/NGIAB-CloudInfra#6]
**Is your feature request related to a problem? Please describe.**

The problem is to implement data assimilation (DA) within NextGen. To properly implement DA, there's a need to restart the model at a specific time. This means the model should provide the state variables at every time step as output and at the same time it must be able to accept the state variables as inputs.

To provide an example, assume you run the model from 2000 to 2022. Now if you want to get the streamflow for the year 2023, one option is to run the model all over again from 2000 to 2023. The other option is to simply run it just for the year 2023. However, to properly make this simulation, the model should accept the initial state variables from where we stopped the model (12/31/2022)  Otherwise, the result for the year 2023 will be significantly different for these two scenarios. 

**Describe the solution you'd like**
Currently, NextGen only provides Q-out (streamflow) for each catchment in a cat-id.csv file. We need that nextgen to output a new CSV file (it should be a human-readable file that is usually called a restart file) where the state variable values are reported there. In addition, the restart file should be used as an additional input file for running the NextGen. In summary, NextGen needs to provide state variables and also use those state variables as input at each time step. This functionality is doable by using BMI get and set variable features but it needs to be applied within NextGen.

**Comment by arpita0911patel** [comment]
Closing this issue as it needs to be address in ngen repo.
