### ISSUE TITLE
x86 build issue with latest code

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB-CloudInfra#62]
While trying to build the x86 image locally on windows machine using below commands , ngen-deps and troute images are created successfully but ngen image build is failing with below error.
 
docker buildx build --tag awiciroh/ngen-deps:latest-x86-test -f Dockerfile.ngen-deps . 
docker push awiciroh/ngen-deps:latest-x86-test          
 
docker buildx build --tag awiciroh/t-route:latest-x86-test -f Dockerfile.t-route .                                          
docker push awiciroh/t-route:latest-x86-test                                                     
  
docker buildx build --tag awiciroh/ngen:latest-x86-test -f Dockerfile.ngen . 
docker push awiciroh/ngen:latest-x86-test   
  
docker buildx build --tag awiciroh/ciroh-ngen-image:latest-x86-test -f Dockerfile . 
docker push awiciroh/ciroh-ngen-image:latest-x86-test
 

## Current behavior

> docker buildx build --tag awiciroh/ngen:latest-x86-test -f Dockerfile.ngen .
[+] Building 0.5s (15/16)
=> [internal] load build definition from Dockerfile.ngen                                                                       0.0s
=> => transferring dockerfile: 9.00kB                                                                                          0.0s
=> [internal] load .dockerignore                                                                                               0.0s
=> => transferring context: 2B                                                                                                 0.0s
=> [internal] load metadata for docker.io/awiciroh/t-route:latest                                                              0.0s
=> [internal] load metadata for docker.io/awiciroh/ngen-deps:latest                                                            0.0s
=> FROM docker.io/awiciroh/t-route:latest                                                                                      0.0s
=> [internal] load build context                                                                                               0.0s
=> => transferring context: 79B                                                                                                0.0s
=> [rocky_build_ngen 1/8] FROM docker.io/awiciroh/ngen-deps:latest                                                             0.0s
=> CACHED [rocky_init_repo 2/3] WORKDIR /ngen                                                                                  0.0s
=> CACHED [rocky_init_repo 3/3] RUN cd /ngen     && if [ "x$COMMIT" != "x" ]; then         git clone --single-branch --branch  0.0s
=> CACHED [rocky_build_ngen 2/8] COPY --chown= --from=rocky_init_repo /ngen/ngen /ngen/ngen                                    0.0s
=> CACHED [rocky_build_ngen 3/8] COPY --chown= --from=awiciroh/t-route:latest /ngen/t-route/wheels /tmp/t-route-wheels         0.0s
=> CACHED [rocky_build_ngen 4/8] COPY --chown= --from=awiciroh/t-route:latest /ngen/t-route/requirements.txt /tmp/t-route-req  0.0s
=> CACHED [rocky_build_ngen 5/8] RUN if [ "ON" == "ON" ]; then         chgrp -R ${USER} /usr/local/lib*/python3.* ;         c  0.0s
=> CACHED [rocky_build_ngen 6/8] COPY fix_io_sub_7551590a415b89026559c1c570d4154e4746161b.patch /ngen/ngen/fix_io_sub.patch    0.0s
=> ERROR [rocky_build_ngen 7/8] RUN cd /ngen/ngen && git apply --reject --whitespace=fix     fix_io_sub.patch                  0.4s
------
> [rocky_build_ngen 7/8] RUN cd /ngen/ngen && git apply --reject --whitespace=fix     fix_io_sub.patch:
#0 0.392 Checking patch extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_aorc.c...
#0 0.392 error: while searching for:
#0 0.392         return -1;?
#0 0.392     }?
#0 0.392     int seen_non_whitespace = 0;?
#0 0.392     char c;?
#0 0.392     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.392         // keep track if this line has seen any char other than space or tab?
#0 0.392         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.392
#0 0.392 error: patch failed: extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_aorc.c:480
#0 0.392 Checking patch extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_pet.c...
#0 0.392 error: while searching for:
#0 0.392         return -1;?
#0 0.392     }?
#0 0.392     int seen_non_whitespace = 0;?
#0 0.392     char c;?
#0 0.392     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.392         // keep track if this line has seen any char other than space or tab?
#0 0.392         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.392
#0 0.392 error: patch failed: extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_pet.c:497
#0 0.392 Checking patch extern/cfe/cfe/forcing_code/src/bmi_aorc.c...
#0 0.393 error: while searching for:
#0 0.393         return -1;?
#0 0.393     }?
#0 0.393     int seen_non_whitespace = 0;?
#0 0.393     char c;?
#0 0.393     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.393         // keep track if this line has seen any char other than space or tab?
#0 0.393         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.393
#0 0.393 error: patch failed: extern/cfe/cfe/forcing_code/src/bmi_aorc.c:480
#0 0.393 Checking patch extern/cfe/cfe/forcing_code/src/bmi_pet.c...
#0 0.393 error: while searching for:
#0 0.393         return -1;?
#0 0.393     }?
#0 0.393     int seen_non_whitespace = 0;?
#0 0.393     char c;?
#0 0.393     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.393         // keep track if this line has seen any char other than space or tab?
#0 0.393         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.393
#0 0.393 error: patch failed: extern/cfe/cfe/forcing_code/src/bmi_pet.c:497
#0 0.393 Checking patch extern/cfe/cfe/src/bmi_cfe.c...
#0 0.394 error: while searching for:
#0 0.394         return -1;?
#0 0.394     }?
#0 0.394     int seen_non_whitespace = 0;?
#0 0.394     char c;?
#0 0.394     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.394         // keep track if this line has seen any char other than space or tab?
#0 0.394         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.394
#0 0.394 error: patch failed: extern/cfe/cfe/src/bmi_cfe.c:2814
#0 0.394 Checking patch extern/evapotranspiration/evapotranspiration/forcing_code/src/bmi_aorc.c...
#0 0.395 error: while searching for:
#0 0.395         return -1;?
#0 0.395     }?
#0 0.395     int seen_non_whitespace = 0;?
#0 0.395     char c;?
#0 0.395     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.395         // keep track if this line has seen any char other than space or tab?
#0 0.395         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.395
#0 0.395 error: patch failed: extern/evapotranspiration/evapotranspiration/forcing_code/src/bmi_aorc.c:480
#0 0.395 Checking patch extern/evapotranspiration/evapotranspiration/src/bmi_pet.c...
#0 0.396 error: while searching for:
#0 0.396         return -1;?
#0 0.396     }?
#0 0.396     int seen_non_whitespace = 0;?
#0 0.396     char c;?
#0 0.396     for (c = fgetc(fp); c != EOF; c = fgetc(fp)) {?
#0 0.396         // keep track if this line has seen any char other than space or tab?
#0 0.396         if (c != ' ' && c != '\t' && c != '\n')?
#0 0.396
#0 0.396 error: patch failed: extern/evapotranspiration/evapotranspiration/src/bmi_pet.c:510
#0 0.397 Applying patch extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_aorc.c with 1 reject...
#0 0.397 Rejected hunk #1.
#0 0.398 Applying patch extern/SoilFreezeThaw/SoilFreezeThaw/forcing_code/src/bmi_pet.c with 1 reject...
#0 0.398 Rejected hunk #1.
#0 0.398 Applying patch extern/cfe/cfe/forcing_code/src/bmi_aorc.c with 1 reject...
#0 0.398 Rejected hunk #1.
#0 0.398 Applying patch extern/cfe/cfe/forcing_code/src/bmi_pet.c with 1 reject...
#0 0.398 Rejected hunk #1.
#0 0.398 Applying patch extern/cfe/cfe/src/bmi_cfe.c with 1 reject...
#0 0.398 Rejected hunk #1.
#0 0.399 Applying patch extern/evapotranspiration/evapotranspiration/forcing_code/src/bmi_aorc.c with 1 reject...
#0 0.399 Rejected hunk #1.
#0 0.399 Applying patch extern/evapotranspiration/evapotranspiration/src/bmi_pet.c with 1 reject...
#0 0.399 Rejected hunk #1.
------
Dockerfile.ngen:98
--------------------
  97 |     # Apply the IO fix to submodules, once they all get patched/merged, this can be dropped...
  98 | >>> RUN cd ${WORKDIR}/ngen && git apply --reject --whitespace=fix \
  99 | >>>     #patch the submodules
100 | >>>     fix_io_sub.patch
101 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd ${WORKDIR}/ngen && git apply --reject --whitespace=fix     fix_io_sub.patch" did not complete successfully: exit code: 1

**Comment by JoshCu** [comment]
the images need specific tags for the first three stages
```bash
docker build -f Dockerfile.ngen-deps -t awiciroh/ngen-deps . --no-cache \
&& docker build -f Dockerfile.t-route -t awiciroh/t-route . --no-cache \
&& docker build -f Dockerfile.ngen -t awiciroh/ngen . --no-cache \
&& docker build -f Dockerfile -t awiciroh/ciroh-ngen-image:latest-x86 . --no-cache
```
it should work running that command

**Comment by arpita0911patel** [comment]
Thank you Josh for adding the command that worked on your end.
