### ISSUE TITLE
Quality of Life improvements to guide.sh and HelloGen

### ISSUE THREAD

**Issue by JoshCu** [CIROH-UA/NGIAB-CloudInfra#69]
During testing I've been repeatedly running the scripts and I think they could benefit from the following

- Remembering the data directory stops you needing to enter the data directory on repeated runs  
- Enabling path auto completion when entering file paths  
- Removing .parquet files that stop ngen running along with output files
- Auto selecting the first catchment nexus and realization file
- Adding the option to pull an image or use a local one (this one may be more useful for dev)

**Comment by arpita0911patel** [comment]
Closing this ticket as its merged to main.
