### ISSUE TITLE
Adding unit testing for the PR validation 

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB-CloudInfra#89]
Run docker using auto mode.
Let's use realization file from : https://github.com/CIROH-UA/NGIAB-CloudInfra/tree/main/config

**Comment by benlee0423** [comment]
Command to run the image in auto mode. Replace image tag with the one built in the Runner, and the location input file in the Runner.
```
docker run --rm -it -v /home/ubuntu/workspace/AWI_03W_113060_003:/ngen/ngen/data awiciroh/ciroh-ngen-image:latest /ngen/ngen/data auto
```

**Comment by benlee0423** [comment]
With `load: true` in build action creates an image locally, but when it referenced from Dockerfiles, it gets the following error.
```
Dockerfile.t-route:14
--------------------
  12 |     ##### Create intermediate Docker build stage for building t-route in Rocky Linux environment
  13 |     ARG TAG_NAME
  14 | >>> FROM awiciroh/ngen-deps:${TAG_NAME} as rocky_init_troute_repo
  15 |     ARG TROUTE_REPO_URL \
  16 |         TROUTE_BRANCH \
--------------------
ERROR: failed to solve: awiciroh/ngen-deps:89-adding-unit-testing-for-the-pr-
```
Revert to `push: true`

**Comment by benlee0423** [comment]
Error message from docker run command.
`the input device is not a TTY`

Remove `it` option from docker run command
```
docker run --rm -v /home/ubuntu/workspace/AWI_03W_113060_003:/ngen/ngen/data awiciroh/ciroh-ngen-image:latest /ngen/ngen/data auto
```
