### ISSUE TITLE
Benchmarking LSTM models on Canada and US basins: CAMELS_spat dataset

### ISSUE THREAD

**Issue by jpcurbelo** [CIROH-UA/NGIAB-CloudInfra#98]
**1.	Requester Information:**

Name: Raymond Spiteri

Institution: University of Saskatchewan

Position: Professor - Computer Science

Email: spiteri@cs.usask.ca

**2.	Project Information:** 

This project focuses on benchmarking Long Short-Term Memory (LSTM) models across Canadian and US basins (from CAMELS_spat, under development). Specifically, we concentrate on hydrological modeling tasks related to extreme precipitation and flood events. Leveraging the shared infrastructure, this initiative serves as a platform for executing models efficiently across diverse basins, thereby contributing to the establishment of a benchmarking standard for LSTM models. 

Jesus Perez Curbelo, Postdoc at the University of Saskatchewan, will be accessing and using the resources and will work under the supervision of Raymond Spiteri and Martyn Clark. We have collaborative efforts with Chaopeng Shen in this research.

Utilizing the [NeuralHydrology](https://joss.theoj.org/papers/10.21105/joss.04050#) library, we plan to replicate published findings from the [CAMELS-US dataset](https://ral.ucar.edu/solutions/products/camels). Additionally, we will employ CAMELS_spat for modeling Canadian basins. The NeuralHydrology library, hosted on [GitHub](https://github.com/neuralhydrology/neuralhydrology), provides the necessary framework for our modeling endeavors.

**3.  Project Description:**

The project involves using and developing LSTM models using virtual environments where we would install the dependencies for the NeuralHydrology library. Also, the software and scripts will be developed in Python including packages such as TensorFlow, PyTorch, and Keras. The data will be stored in `netcdf` and `csv` files.

**4.	Resource Requirements:** 

    Subject to change:

    GPU: 8xA100 (when available) / 4xV100

    CPU: 16 cores

    Memory: 100 GB RAM

    Disk Space: 200 GB HD

**5.	Timeline:** 

Starting as soon as possible and continuing until December 31, 2024
 

**6.	Security and Compliance Requirements:** 

No apply

 
**7.	Approval:** 

No apply

**Comment by arpita0911patel** [comment]
@jameshalgren

**Comment by TrupeshKumarPatel** [comment]
Hello @jpcurbelo,

Once you have UA credentials to log into VPN, please [email me](mailto:trpatel2@crimson.ua.edu?cc=apatel54@ua.edu,jshalgren@ua.edu,pvbangalore@ua.edu&subject=Pantarhei%20Account%20Creation%20Request) for Pantarhei account creation. Could you ensure the email body includes your full name and UA email address (if you have one)?

> [!NOTE]
> Please make sure if multiple users need access, then each user will have to send an email from their account.

**Comment by arpita0911patel** [comment]
@jpcurbelo we will need your phone number to put in VPN request. Please Slack us your number.

**Comment by arpita0911patel** [comment]
@jpcurbelo please share your UA email ID when you get chance on slack. thank you.

**Comment by arpita0911patel** [comment]
VPN Access Request Form is submitted today. Thank you.

**Comment by TrupeshKumarPatel** [comment]
Hello @jpcurbelo ,
Your account is created on Pantarhei. Please send an acknowledgment here to confirm you can access the cluster.

**Comment by arpita0911patel** [comment]
Closing this ticket as Jesus is provided access to Pantarhei.
